### ISSUE TITLE
dayGridMonth option fixedWeekCount not working

### ISSUE THREAD

**Issue by jeremyngodp** [fullcalendar/fullcalendar-react#101]
### Bug Reports
fixedWeekCount is set to false, but the calendar is still showing 6 weeks per month
https://codepen.io/jngodp/pen/PoNgbLP

**Comment by acerix** [comment]
The setting needs to be `false` without quotes.  The string `'false'` in JS evals to `true`.

https://codepen.io/acerix/pen/MWyMgoK?editors=0010
