### ISSUE TITLE
I get no height if i refresh my app (see attatched screenshot)

### ISSUE THREAD

**Issue by Dev-Yol** [fullcalendar/fullcalendar-react#104]
![image](https://user-images.githubusercontent.com/69956128/95644374-cf354f80-0ae8-11eb-96b7-d0228e8ebc7c.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
