### ISSUE TITLE
CSS does not load with localIdentName option in webpack.config

### ISSUE THREAD

**Issue by Simply1993** [fullcalendar/fullcalendar-react#107]
If we use option localIndentName in webpack.config, then react component calendar get incorrect classnames for styles.

For example:
https://codesandbox.io/s/cool-resonance-u1d4z

How we can fix it (except change webpack.config)?

**Comment by davelab** [comment]
any news on this issue?

**Comment by arshaw** [comment]
Almost definitely fixed in [v6.0.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v6.0.0) because the build system is no longer responsible for processing CSS. Please let me know if problems persist.
