### ISSUE TITLE
When the scheduler is connected, the Fullcalendar starts to work incorrectly

### ISSUE THREAD

**Issue by artemkrynkin** [fullcalendar/fullcalendar-react#11]
After connecting the scheduler, the calendar starts to work incorrectly, that using the api methods and that with the usual display an error appears `Uncaught TypeError: equalityFunc is not a function`
<img width="551" alt="Скриншот 2019-04-19 00 44 17" src="https://user-images.githubusercontent.com/6913231/56393189-495e7e00-623c-11e9-93ad-e90abe04a404.png">

**example**:
api methods navigation: https://codesandbox.io/s/o40z811866
default navigation: https://codesandbox.io/s/wqlq3l16j7

Also, when you switch the view, after several times, the calendar starts to appear so:
<img width="554" alt="Скриншот 2019-04-19 00 43 21" src="https://user-images.githubusercontent.com/6913231/56393141-2764fb80-623c-11e9-87b6-1c6c242a04ad.png">
<img width="551" alt="Скриншот 2019-04-19 00 55 37" src="https://user-images.githubusercontent.com/6913231/56393682-db1abb00-623d-11e9-99a7-8e8ea3d7fe0f.png">

Check in api methods navigation: month -> prev/next -> day/week/month/prev/next
Check in default navigation: month -> prev/next -> day/week/month/prev/next

maybe I'm doing something wrong?

but if not used `@fullcalendar/resource-daygrid` and `@fullcalendar/resource-timegrid`, then everything is fine working: https://codesandbox.io/s/rmly58zpmq

**Comment by arshaw** [comment]
it's due to this problem:
https://github.com/fullcalendar/fullcalendar/issues/4606

i will publish v4.1.0 really soon, and upgrading to that will fix your problem

**Comment by artemkrynkin** [comment]
@arshaw thank you

**Comment by arshaw** [comment]
The root problem is fixed in core. Can you try upgrading to 4.1.0 and confirm that it's fixed? If there are still issues I'll reopen this ticket.
