### ISSUE TITLE
eventDrop Drag the element out of the calendar view and release it. All events are disabled

### ISSUE THREAD

**Issue by qiujunbiao** [fullcalendar/fullcalendar-react#112]
fullcalendar-react

eventDrop events

 Drag the element out of the calendar view and release it. All events are disabled

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
