### ISSUE TITLE
Passing custom props to custom view

### ISSUE THREAD

**Issue by phongnm-dev** [fullcalendar/fullcalendar-react#119]
### Feature Requests
Hi, I've created a custom view with fullcalendar, but I can't find anyway to pass custom props to its, it only receive the default props from fullcalendar.
The default props passed to custom view is missing some necessary props like viewRender (viewDidMount)

**Comment by acerix** [comment]
This is not specific to React, there is already a ticket in the main repo:
https://github.com/fullcalendar/fullcalendar/issues/6048
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
