### ISSUE TITLE
Ability to return a react element in eventRender function

### ISSUE THREAD

**Issue by jonlachlan** [fullcalendar/fullcalendar-react#12]
I'd like to be able to return a JSX-style react element in the eventRender function, like in the customEventRender method in this CodePen: 
https://codesandbox.io/embed/p7kyyr14ym

If I try this now I get `TypeError: can't define property "fcSeg": Object is not extensible.`

Let me know if I need to provide more info to describe this.

**Comment by joshuaRuff** [comment]
Because _info.el_  is more than a simple JSX element you can't just replace all of that. However there are some ways you can edit _info.el_ to your liking:

- Add a custom class name to the class string
```javascript
customEventRender = info => {
    // edit the parent's class
    info.el.className = "custom-event-container fc-day-grid-event fc-h-event fc-event fc-start fc-end"
    // edit the child's class
    info.el.children[0].className = "custom-event-container fc-content"
    return info.el
  };
```
- Change Child Content

```javascript
customEventRender = info => {
    info.el.firstChild.innerText = "Text Overwrite"
    return info.el
  };
```

Let me know if there is a certain part of the element you are trying to change and if this info is helpful.

**Comment by jonlachlan** [comment]
Thank you, this is exactly what I wanted to know.

**Comment by arshaw** [comment]
I'm reopening this up because it might be a nice API to allow for returning a JSX element.

I've been thinking about this recently because it came up in the Vue repo (https://github.com/fullcalendar/fullcalendar-vue/issues/14)

**Comment by jonlachlan** [comment]
FYI, it seems that in my codepen I should not have been trying to return a React element that wraps `info.el`, but rather one that wraps or includes something from the `info.event` object. In any case, I think the question was understood, whether eventRender looks for a React element to be returned.

One possible use-case that I was thinking of was to create/use a tooltip component, such as how Antd does their [Popover component](https://ant.design/components/popover/), as an alternative to using Tooltip.js as described in the Fullcalendar docs.

**Comment by stclairdaniel** [comment]
I would love it if this could let us just return arbitrary JSX - it would make things far easier to customize.

**Comment by tgandee79** [comment]
This below seems works for React rendering, but when I use `eventRender` at all and edit the `info.el` the table cell sizing doesn't match. Screenshot below.


```
render(
                    <div class="fc-content">
                        <span class="fc-title">{info.event.title} - {info.event.extendedProps.prop2} - {info.event.extendedProps.prop1}</span>
                    </div>,
                    info.el,
                );
return info.el; 
```

all events are suppose to be on the 29th
![image](https://user-images.githubusercontent.com/1489134/61528166-14ed9000-a9ec-11e9-9357-0b288639efc0.png)


![image](https://user-images.githubusercontent.com/1489134/61528212-32225e80-a9ec-11e9-80a7-90b7ef00e5d3.png)

**Comment by jonlachlan** [comment]
One note, my initial codepen suggested that `eventRender` currently expects to return `info.el`, which was a misunderstanding on my part, and other examples here have repeated that pattern. In reality you modify `info.el` directly and return nothing.

**Comment by RachelScodes** [comment]
Any update on this? Especially as the convention is to use more functional components in react... Looks like the corresponding vue issue was closed without resolution.

**Comment by Daniel-Griffiths** [comment]
I get the same issue as @tgandee79, Using the `ReactDOM.render` works but causes the table cell size to be incorrectly calculated

**Comment by Daniel-Griffiths** [comment]
A temporary fix I found was to force the row height to be automatic, eg:

```
.fc-body .fc-row {
    height: auto !important;
}
```

This overwrites the inline styles that full calendar adds.

**Comment by arshaw** [comment]
If you're curious to know, this will be included in v5 (currently in-development)
**blog post:** https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5

**Comment by stclairdaniel** [comment]
@arshaw Very cool! I'm looking forward to upgrading.

**Comment by Aveesha** [comment]
I picked up on advise on this thread and did something like this - 
` eventRender={(info) => {
          const image = document.createElement('div');
          const status = info.event.extendedProps.status.toLowerCase();
          image.setAttribute('class', 'request-calendar-icon');
          info.el.append(image);
      }}`

The colors listed out in the CSS appear muted/dull. I've used the same green color (#0acf4b) on FullCalendar vs another custom React Component, but the opacity levels seem to be very different?

![Screen Shot 2020-03-03 at 5 37 04 PM](https://user-images.githubusercontent.com/18519895/75830218-d5569700-5d75-11ea-8d86-d7240feddee4.png)


![image](https://user-images.githubusercontent.com/18519895/75830173-adffca00-5d75-11ea-8e3d-c855928ac9fa.png)

**Comment by l3szcz** [comment]
Just a heads up for anyone trying to use ReactDOM.render to return React Component for calendar event. By default the created ReactDOM tree is not removed which lead to choppy interactions with events in my case. You should add eventDestroy handler like this:

eventRender:
```
eventRender={info => {
          ReactDOM.render(
            <Event></Event>,
            info.el.querySelector(".fc-content")
          );
          return info.el;
        }}
```

eventDestory:
```
eventDestroy={info =>
          ReactDOM.unmountComponentAtNode(info.el.querySelector(".fc-content"));
        }}
```

**Comment by arshaw** [comment]
this is available in [the latest v5-beta](https://fullcalendar.io/blog/2020/04/new-ui-features-beta)

here's an example using the new `eventContent` setting:
https://github.com/fullcalendar/fullcalendar-example-projects/blob/v5/react/src/DemoApp.jsx#L38

**Comment by arshaw** [comment]
vdom nodes are accepted in many places, not just for events. please see all the *Content settings in the upgrade guide: https://fullcalendar.io/docs/v5/upgrading-from-v4

**Comment by leesh22** [comment]
Also having the same issue as @tgandee79 but with the resourceTimelinePlugin. The calendar cells are not adjusting to the event size on the first render, using the `5.0.0-beta.2` function `eventContent`

**Comment by arshaw** [comment]
Hey @leesh22 , could you post a [runnable, stripped-down demonstration of the bug](https://fullcalendar.io/reduced-test-cases)? also, maybe try v5.0.0-beta.3. i fixed a number of event positioning bugs in that release

**Comment by leesh22** [comment]
@arshaw Ah I didn't realise there was a beta.3 - that update fixed the issue :) - thanks for the speedy response!

**Comment by Gustl22** [comment]
What strategy do I have to use to **wrap existing content** with a React component e.g. with [MUI Tooltip](https://material-ui.com/components/tooltips/)? I [posted this solution](https://stackoverflow.com/a/63135917/5164462), but then I noticed that it doesn't fit for different view types, e.g. `listMonth`. Can I somehow access the original `eventContent`?

**Comment by arshaw** [comment]
Sorry, I never updated this ticket. This is now possible in v5:
https://fullcalendar.io/docs/react#content-injection

@Gustl22 the [eventDidMount](https://fullcalendar.io/docs/event-render-hooks) hook is likely what you need

**Comment by Gustl22** [comment]
@arshaw Unlike [Tooltip.js](https://fullcalendar.io/docs/v4/event-tooltip-demo) I cannot attach the tooltip to a rendered element. The content must be wrapped inside the [MUI Tooltip](https://material-ui.com/components/tooltips/) before rendering:

ˋˋˋ
<Tooltip title="Tooltip">
  <Content>Arrow</Content>
</Tooltip>
ˋˋˋ

Whereas ˋContentˋ has to be the original ˋeventContentˋ dependent on the view (month / list etc.). Then I return the Element via ˋeventContentˋ.
Any ideas?

**Comment by nkemcels** [comment]
This issue is still there

**Comment by bahachammakhi** [comment]
@Gustl22  same problem here I used eventContent hook todo that but still can't accesss the wrapper

**Comment by Gustl22** [comment]
@bahachammakhi I opened an issue for that, you can see, like and comment your opinion there https://github.com/fullcalendar/fullcalendar/issues/5927 Thank you! :pray:
