### ISSUE TITLE
Fullcalendar v5 error node-sass electron

### ISSUE THREAD

**Issue by RactivussDevs** [fullcalendar/fullcalendar-react#122]
I'm having the error  Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (80) when building an electron app using Fullcalendar. The complete error is: ERROR in ./node_modules/@fullcalendar/daygrid/main.css (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??ref--6-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/@fullcalendar/daygrid/main.css)

My current environment versions are:

electron version: 9.4.0
electron-rebuild: 1.11.0
node-sass 4.14.1
postcss-loader: 3.0.0
sass-loader: 4.14.1
@fullcalendar/core: 5.3.1
@fullcalendar/react: 5.3.1
@fullcalendar ....

node version: 12.13.0
npm version: 6.12.0

This doesn't happen when i'm building a normal app for the browser. Please help me!

**Comment by RactivussDevs** [comment]
...

**Comment by acerix** [comment]
I believe that means you need to run `npm rebuild node-sass`.

https://stackoverflow.com/a/41082773

**Comment by RactivussDevs** [comment]
Mmm.. I already done that but didn't work. I thought that it would be due to the node version but it didn't work neither. Sorry for my english.

**Comment by RactivussDevs** [comment]
If there's anyone who need help in this, can check this issue: https://github.com/sass/node-sass/issues/1682
Check the answer of `hdytsgt`. It helps me a lot.
