### ISSUE TITLE
FullCalender +more option issue when custom button is added

### ISSUE THREAD

**Issue by priyankush-siloria** [fullcalendar/fullcalendar-react#126]
I have implement the full calendar in reactjs code. This is my code
<FullCalendar
    defaultView="dayGridMonth"
    headerToolbar={{
        left: "prev,next today myCustomButton",
        center: "title",
        right: "dayGridMonth,timeGridWeek,timeGridDay,listWeek",
    }}
    dayMaxEventRows={3}
    customButtons={{
        myCustomButton: {
        text: "Create Event",
        class: "create-event color-btn px-2 py-1",
        click: () => {
            this.showModal("add");
        },
        },
    }}
    editable={true}
    selectable={true}
    droppable={true}
    selectMirror={true}
    plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin]}
    events={eventData}
/>
Everything is working fine but when i am click on +more event the popup is not showing, 

If i remove **customButtons** code then its working fine

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
