### ISSUE TITLE
Increasing an event's size by a single slot doesn't cause a passed component to update

### ISSUE THREAD

**Issue by tkgwheeler** [fullcalendar/fullcalendar-react#128]
### Reduced Test Case
[REDUCED TEST CASE](https://codesandbox.io/s/6209d?file=/src/DemoApp.jsx).
In my test case I simply added a console log in componentDidUpdate.

### Bug Description
A component passed to the eventContent hook is not being updated when you **increase** the event size by only one slot in either direction.

Steps to reproduce:
1. Pass a component to FC's eventContent hook that performs some action in the componentDidUpdate method
2. Initiate an eventResize action by dragging the event's edges (start or end)
3. Increase the event's size by a singular slot
4.  Observe that the componentDidUpdate was not triggered
5. Observe that if you drag the end by more than one slot then the update is triggered on each slot beyond the first.
6. Observe that decreasing the size of an event does not suffer from the same issue with the first slot

Expected behaviour:
The componentDidUpdate would have been triggered when you increase the event via resize by a single day. In our case we ascertain the impact on a Resource's availability whilst dragging or resizing an event. As a result of the above, increasing an event's size by a singlular day isn't triggering our calculation. Dragging, resizing to a smaller size or increasing the size beyond a single slot all work as expected.

**Comment by arshaw** [comment]
@tkgwheeler , things are actually working be design. When you resize the event to the first slot, a new "mirror" event is rendered in its place. When you resize to the second slot, the "mirror" event is updated. That's what's causing componentDidUpdate to fire only on the second time.

Part of the solution is to ignore when `eventContent` fires with the `isMirror` flag is set to `true`.  https://fullcalendar.io/docs/event-render-hooks

However, there is no way to explicitly monitor when the user resizes the event while they're dragging. There's a feature request for that: https://github.com/fullcalendar/fullcalendar/issues/4053

Something tells me you simply want to control the regions the event can/can't be resized into. This callback will give you that control: https://fullcalendar.io/docs/eventAllow

**Comment by tkgwheeler** [comment]
@arshaw , I'm not looking to control the regions that the event can be resized into. I'm actually displaying little numbers within each slot. Those numbers represent the remaining available hours that resource has for the day. As an event is dragged I'd like to update those values so the user can immediately see what impact it would have on the resource's availability _if they were to drop the event._  I've been trying to acheive this by capturing the eventContent's component updates that occur when the event is being dragged, but as mentioned this does not occur when moved by a single day (or to a new resource). In those cases I currently just have to wait and rely on the event drop.

![availabilityIndicators](https://user-images.githubusercontent.com/15182849/112344155-bb0e9480-8cbb-11eb-8a83-55b31ec623e3.JPG)

![availabilityIndicatorsAfterDrag](https://user-images.githubusercontent.com/15182849/112345756-3ae92e80-8cbd-11eb-87c4-4f1eec2b7249.JPG)


So yeah, looks like that feature request for specific event resize and drag operations is what I would need in this case.
