### ISSUE TITLE
TypeError: Cannot read property 'duration' of undefined

### ISSUE THREAD

**Issue by MattDEV02** [fullcalendar/fullcalendar-react#136]
### TypeError: Cannot read property 'duration' of undefined

I have create simple FullCalendar React component:

// My code

 <FullCalendar
            plugins={[dayGridPlugin]}
            initialView="dayGridMonth"
            events={[
               { title: 'event 1', date: '2019-04-01' },
               { title: 'event 2', date: '2019-04-02' }
            ]}
         />

------------------------------------------------------------------

dynamicOptionOverrides: CalendarOptions,
  47 |   localeDefaults,
  48 | ): ViewSpec {
> 49 |   let durationInput =
  50 |     viewDef.overrides.duration ||
  51 |     viewDef.defaults.duration ||
  52 |     dynamicOptionOverrides.duration ||

let overrideConfigs = parseViewConfigs(optionOverrides.views)
  37 |   let viewDefs = compileViewDefs(defaultConfigs, overrideConfigs)
  38 | 
> 39 |   return mapHash(viewDefs, (viewDef) => buildViewSpec(viewDef, overrideConfigs, optionOverrides, dynamicOptionOverrides, localeDefaults))
  40 | }
  41 | 
  42 | function buildViewSpec(

61 | let newHash = {}
  62 | 
  63 | for (let key in hash) {
> 64 |   newHash[key] = func(hash[key], key)
     | ^  65 | }
  66 | 
  67 | return newHash

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
