### ISSUE TITLE
index.js:1 Warning: `NaN` is an invalid value for the `right` css style property.

### ISSUE THREAD

**Issue by pig800509** [fullcalendar/fullcalendar-react#138]
### Bug Reports
If set props `weekNumberCalculation="ISO"` or `firstDay={1}`, and change "timeGridWorkWeek(`weekends: false`)"  to "timeGridWeek(`weekends: true`)", then it will show ``index.js:1 Warning: `NaN` is an invalid value for the `right` css style property.``

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
