### ISSUE TITLE
Firefox Date Formatter bug?

### ISSUE THREAD

**Issue by nabati** [fullcalendar/fullcalendar-react#142]
### Bug Reports

When setting the slotLabelFormat.hour to '2-digit', you get the correct behavior in chrome (left) but the wrong behavior in Firefox (right)

![image](https://user-images.githubusercontent.com/1499050/120614197-442e0e80-c457-11eb-9ca9-d296e041557e.png)

https://codesandbox.io/s/fullcalendar-react-time-formatter-xbrmu?file=/src/calendar.js

**Comment by acerix** [comment]
It's up to the browser how to render times, you can use use a formatting plugin for more control:

https://fullcalendar.io/docs/moment-plugin
