### ISSUE TITLE
dayMaxEventRows is not working in React

### ISSUE THREAD

**Issue by killcodeX** [fullcalendar/fullcalendar-react#143]
I am trying to use dayMaxEventRows in my React core project, I am trying to pass prop dayMaxEventRows in my component but it doesn't reflect any changes, I am pasting my code below,

`
          <FullCalendar
            eventClick={onEventClick}
            themeSystem="bootstrap"
            initialView="resourceTimeGridDay"
            eventTextColor="#4A4A4A"
            initialDate={currentDate}
            plugins={[
              interactionPlugin,
              resourceTimeGridPlugin,
              bootstrapPlugin,
              customViewPlugin,
            ]}
            resources={resources.slice(...currentResourcesRange)}
            dayMaxEvents={true}
            dayMaxEventRows={true,5}
            //eventLimit={true,5}
            events={events}
            slotDuration="00:15:00"
            slotLabelInterval="01:00:00"
            slotMinTime="08:00"
            slotMaxTime="22:00"
            nowIndicator={true}
            scrollTime={moment().format("HH:mm")}
            slotLaneClassNames="fc-slot-lane"
            slotLaneContent={({ date }) => moment(date).format("hh:mm A")}
            slotLabelFormat={{
              hour: "numeric",
              minute: "2-digit",
              meridiem: true,
            }}
            eventTimeFormat={{
              hour: "2-digit",
              minute: "2-digit",
              meridiem: true,
            }}
            datesSet={({ startStr: date }) => onDateChange(date)}
            dateClick={onDateClick}
            headerToolbar={{
              left: "",
              center: "prev today title next",
              right: "",
            }}
            titleFormat={{
              month: "long",
              year: "numeric",
              day: "numeric",
              weekday: "long",
            }}
          />
`

![Opera Snapshot_2021-06-05_201701_app gobony in](https://user-images.githubusercontent.com/43428865/120895542-0a1d6200-c63b-11eb-897b-8d226f7da8e5.png)

Here I am trying to limit the number of events to a total of 5 and when the user click, It will pop over the rectangular panel with a full list of events for that time

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
