### ISSUE TITLE
Localize Fullcalendar with React on Firefox and Safari

### ISSUE THREAD

**Issue by MrGentile93** [fullcalendar/fullcalendar-react#145]
I'm using FullCalendar plugin for React (v5) on Metronic by KeenThemes and I've tried to localize it in Italian. I'm following the documentation and the snippet below renders correctly on Chrome and Edge, but on Firefox and Safari the months and days are displayed in English (while the rest of the interface is correctly localized).

Here's a screenshot: ![NZyQS](https://user-images.githubusercontent.com/59519959/122541505-fbb34b00-d029-11eb-924b-70470e170eba.png)

`import FullCalendar from '@fullcalendar/react'`
`import dayGridPlugin from '@fullcalendar/daygrid'`
`import interactionPlugin from '@fullcalendar/interaction'`
`import timeGrid from "@fullcalendar/timegrid"`
`import bootstrapPlugin from "@fullcalendar/bootstrap"`
`import all from "@fullcalendar/core/locales-all"`
  
`<FullCalendar`
    `plugins={[dayGridPlugin, interactionPlugin, timeGrid, bootstrapPlugin]}`
  `  headerToolbar={{`
    `  left: 'prev,next today',`
    `  center: 'title',`
     ` right: 'dayGridMonth,timeGridWeek,timeGridDay'`
   ` }}`
   ` weekends={true}`
   ` themeSystem="bootstrap"`
   ` locales={all}`
   ` locale={"it"}`
   ` initialView="dayGridMonth"`
    `selectable={true}`
    `editable={true}`
`/>`

I've tried to change the localization option in various ways, like loading only italian localization instead of all of them, renaming the localization files to switch english and italian. I've also tried clearing cache and all, running it on multiple computers but I can't make it to work on those browsers.

I've also noticed that if I try to run the following snippet:

`const event = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));`
`const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };`
`console.log(event.toLocaleDateString('it-IT', options));`
`// expected output: giovedì 20 dicembre 2012`

It prints the wrong output when executed in a console inside the FullCalendar page in Firefox and Safari, while it works in the same browsers when executed in other pages.

These are the exact versions of the fullcalendar packages I'm using: fullcalendar/bootstrap@5.7.0, fullcalendar/core@5.7.0, fullcalendar/daygrid@5.7.0, fullcalendar/interaction@5.7.0, fullcalendar/list@5.7.0, fullcalendar/react@5.7.0, fullcalendar/timegrid@5.7.0

I've tried to remove all the packages but react and fullcalendar to reproduce the error in a clean environment and it is still present.

How can I resolve this issue?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I don't have Safari to test with at the moment, but I get the translations in this demo using Firefox:

https://fullcalendar.io/docs/locale-demo
