### ISSUE TITLE
Events are placed in the calendar, if they are dragged inside position: absolute container

### ISSUE THREAD

**Issue by maximAlekseev** [fullcalendar/fullcalendar-react#148]
Hello!

Having strange issue with my modal with external events. I have a timeline calendar, full page width, and modal with absolute position, on top of the calendar.
The issue is that if you drag the event from this modal a bit, inside the same modal - event is dropped into calendar into the cell behind modal.
Expected behavior: event is only dropped to calendar if it's moved to calendar area, but inside modal it can be moved anywhere, event should not be applied.

I've taken the demo example from the docs (https://fullcalendar.io/docs/external-dragging) and changed styling a bit, so events container is no top of calendar. You can check "remove after drop" checkbox and try to move events inside their container. Even if an event was not dropped in the calendar - it still ends up in it.

Link to Codepen - https://codepen.io/maximalekseev/pen/jOmVRjw

Current behavior -
![ext-events](https://user-images.githubusercontent.com/29151880/125443504-b4f1c39a-3e76-430a-baca-f44830fdbc58.gif)

Thanks in advance!

**Comment by acerix** [comment]
I believe this existing ticket captures this need. Even though that is referring to another calendar being in front, it seems like the same issue that dragging within a modal in front of a calendar should not allow dropping events on the calendar that is behind:
https://github.com/fullcalendar/fullcalendar/issues/5026
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
