### ISSUE TITLE
CodePen import statements not working

### ISSUE THREAD

**Issue by Isoaxe** [fullcalendar/fullcalendar-react#153]
Hey guys. I'm attempting to run a simple `FullCalendar` as a demonstration of a seperate bug, but can't seem to get imports working with `React`. I have imported other packages such as `react-modal` as demonstrated [here](https://codepen.io/isoaxe/pen/yLbmBeY), so I'm not sure what I'm doing incorrectly with `FullCalendar`.

I've tried importing `npm` packages in the usual way of the form `import FullCalendar from "@fullcalendar/react";` (though the url gets autocorrected by CodePen). I have also tried importing via settings -> JS in CodePen, which has the form `import FullcalendarReact from "https://cdn.skypack.dev/@fullcalendar/react@5.9.0";`.

Unfortunately neither of these import statements worked for me as they did with the `react-modal` example I linked. If I attempt to render the calendar component with either of these turned on, the screen turns white with no errors logged.

I've forked a simple `create-react-app` template and added a component implementing `FullCalendar` in this [demonstration](https://codepen.io/isoaxe/pen/eYWwxYz).

Any help on what the issue might be would be much appreciated.

**Comment by Isoaxe** [comment]
As some additional info, I can get the `FullCalendar` component working by loading the following external script: 
`https://cdn.jsdelivr.net/npm/@fullcalendar/react@5.9.0/dist/main.cjs.min.js`
However, the issue persists with the plugins. Loading them in the same manner does not work. Listed below for completeness:
`https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@5.9.0/main.global.min.js`
`https://cdn.jsdelivr.net/npm/@fullcalendar/list@5.9.0/main.global.min.js`

**Comment by acerix** [comment]
I'm not sure the React component will work like that in Codepen but there's a debug template on CodeSandbox you can use:

https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/master/react?file=/src/DemoApp.jsx

**Comment by Isoaxe** [comment]
That's a pity. I'll fork the template as you suggest and use that instead. Cheers!
