### ISSUE TITLE
Can't drag, create or edit events with next.js

### ISSUE THREAD

**Issue by butterfly-valley** [fullcalendar/fullcalendar-react#159]
### Bug Reports

On a next.js app I can't drag, edit or create events with editable={true}. The body tag does not toggle between empty class and 'fc-unselectable' upon mouse dragging like it usually would so it seems like a css issue.

To reproduce please follow the steps below:

git clone 'https://github.com/butterfly-valley/text-react-fcallendar.git'
npm install
npm or yarn next dev

It is an empty project with just bare minimum to reproduce the behaviour.

**Comment by acerix** [comment]
Some workarounds are needed for Next, does it work using the example project?

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/next

**Comment by butterfly-valley** [comment]
Yes, I applied the workarounds to get it going, you can safely clone and run the project.

**Comment by butterfly-valley** [comment]
Sorry, did not get to the _app.tsx and css part. Will try tomorrow and report.

**Comment by butterfly-valley** [comment]
So I have added a babel.config.js and imported the styles into _app.js, but the issue remains with next@12.0.4 at least. The example project runs fine but is somewhat outdated when it comes to its dependencies. I have updated the repo for you to try my setup. Thanks for looking into this.

**Comment by acerix** [comment]
I just checked your demo and noticed the "interaction" plugin is missing, that's required for event dragging:

https://fullcalendar.io/docs/editable#required-plugin
