### ISSUE TITLE
Extra data gets removed from event object

### ISSUE THREAD

**Issue by tlays11** [fullcalendar/fullcalendar-react#16]
### Bug Reports
Here is my react component

```
import * as React from 'react'
import FullCalendar from '@fullcalendar/react'
import { EventInput } from '@fullcalendar/core'
import dayGridPlugin from '@fullcalendar/daygrid'
import timeGridPlugin from '@fullcalendar/timegrid'
import interactionPlugin from '@fullcalendar/interaction' // needed for dayClick

interface DemoAppState {

}

export default class DemoApp extends React.Component<{}, DemoAppState> {

  calendarComponentRef = React.createRef<FullCalendar>()

  constructor(props: {}) {
    super(props)
  }

  render() {
    return (
<FullCalendar
                defaultView="dayGridMonth"
                header={{
                  left: 'prev,next today',
                  center: 'title',
                  right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
                }}
                plugins={[ dayGridPlugin, timeGridPlugin, interactionPlugin, listPlugin]}
                ref={ this.calendarComponentRef }
                events={ [{id: 1, start: "2019-05-25 09:00:00", description: "this gets removed" }] }
                eventClick={ (event) => console.log(event.event) }
              />
    )
  }
}
```

event.description is undefined, the property gets removed.

Would like to just have access to the full event object rather than have to keep two copies of the array and search each time.

**Comment by joshuaRuff** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](https://fullcalendar.io/reduced-test-cases)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by mostlyfabulous** [comment]
I can access the description property with an eventClick (look for extendedProps): 
![image](https://user-images.githubusercontent.com/15062048/59152037-b3500400-89f1-11e9-96fb-f5a3d3820ba0.png)

**Comment by pgiani** [comment]
check inside `extendedProps`

[Check the Docs](https://fullcalendar.io/docs/event-object)

extendedProps | A plain object holding miscellaneous other properties specified during parsing. Receives properties in the explicitly given extendedProps hash as well as other non-standard properties.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this discussion captures this need:
https://github.com/fullcalendar/fullcalendar-react/issues/65
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
