### ISSUE TITLE
Resource timeline week view - now indicator truncating time

### ISSUE THREAD

**Issue by gregdymek** [fullcalendar/fullcalendar-react#165]
hi guys,
is it possible to setup resource timeline week view so now indicator isn't truncating time?
here is an example:
https://codepen.io/gregdymek/pen/zYEpLEE
best regards,
Greg

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6175
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
