### ISSUE TITLE
Events are not loading on weekends.

### ISSUE THREAD

**Issue by dayaachra** [fullcalendar/fullcalendar-react#170]
Many times the events are not loading on weekends. **It only happens on weekends.** After few time it is automatically loaded. Can you please help me, What is the issue?
![full-calander](https://user-images.githubusercontent.com/99157752/152721178-b73dc73d-7dc5-44e7-894e-72bab8ccaebe.jpg)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
