### ISSUE TITLE
Global CSS cannot be imported from within node_modules error

### ISSUE THREAD

**Issue by saptisunil** [fullcalendar/fullcalendar-react#178]
Here is my code block i am able to get an error error - ./node_modules/@fullcalendar/common/main.css
Global CSS cannot be imported from within node_modules.
```
import React from 'react'
import FullCalendar from '@fullcalendar/react' // must go before plugins
import dayGridPlugin from '@fullcalendar/daygrid' // a plugin!

export default class Calender extends React.Component {
  render() {
    return (
        <div className='leads-container'>
          Calender
          <FullCalendar
            plugins={[ dayGridPlugin ]}
            initialView="dayGridMonth"
            weekends={false}
            events={[
              { title: 'event 1', date: '2019-04-01' },
              { title: 'event 2', date: '2019-04-02' }
            ]}
          /> 
        </div>
    )
  }
```
How to solve Global CSS cannot be imported from within node_modules. this error in nextjs ? Thanks in Advance

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by durdenx** [comment]
Same error. See https://github.com/vercel/next.js/issues/19936#issuecomment-740509781
