### ISSUE TITLE
@fullcalendar/moment-timezone Not working properly with Yarn

### ISSUE THREAD

**Issue by ABAschedules** [fullcalendar/fullcalendar-react#179]
It is the same error message as https://github.com/fullcalendar/fullcalendar/issues/4530

It works when I use npm install --save @fullcalendar/moment-timezone 

but it doesnt work when I use yarn add @fullcalendar/moment-timezone

My project requires Yarn

Can you fix this in Yarn? (Not reproducible with code)

**Comment by acerix** [comment]
I tried this example project and have no issue installing or building with yarn:

https://github.com/fullcalendar/fullcalendar-example-projects/tree/master/moment-timezone

Please post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is a bug.

**Comment by ABAschedules** [comment]
@acerix I ran that example and when I change the timeZone parameter, the times don't change. Are you seeing the same thing?
