### ISSUE TITLE
`columnHeaderHtml` not worked  when passing React node

### ISSUE THREAD

**Issue by abgaryanharutyun** [fullcalendar/fullcalendar-react#18]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

(Please erase the above text and begin typing. Thanks!)

**Comment by joshuaRuff** [comment]
Hey @abgaryanharutyun, did you mean to post this? It looks like you just copy and pasted some text from the issue instructions. I'll close this ticket, if you do have an issue feel free to open another ticket with the linked issue and test case. Blessings!
