### ISSUE TITLE
Supprot React 17 in peer dependency declaration

### ISSUE THREAD

**Issue by tomdracz** [fullcalendar/fullcalendar-react#182]
With the support added for React 18, we've ended up with the following peer dependency declarations:

https://github.com/fullcalendar/fullcalendar-react/blob/master/package.json#L47-L48

```
  "peerDependencies": {
    "react": "^16.7.0 || ^18",
    "react-dom": "^16.7.0 || ^18"
  },
```

This will trigger incorrect peer dependency warning for React 17, even though I don't think it should. Do we need `^17` be included as the version also?

**Comment by Jule-** [comment]
This is **breaking** change.

1. Is there any reason to drop support of `react@^17`?
2. If you want to drop support for `react@^17`, please bump major version.
3. If you don't want to, just add support to `react@^18` (`"react": "^16.7.0 || ^17 || ^18"`)

Thanks for cleaning this up! :slightly_smiling_face:

**Comment by tomdracz** [comment]
For what it's worth, that looks like dependency setting mistake rather than actual support being dropped for React 17. Why the hell would React 16.7 be supported!

I'm running the latest version against React 17 without any problems FYI.

Either way, we need a new version out to sort this out.

**Comment by Jule-** [comment]
Ping @arshaw :wink:

**Comment by arshaw** [comment]
This is a mistake. I will fix this ASAP.

**Comment by arshaw** [comment]
I released the fix in v5.11.1. Can someone please confirm?

**Comment by tomdracz** [comment]
Can confirm 5.11.1 fixes this. Thanks @arshaw !

**Comment by Jule-** [comment]
Thanks @arshaw ! :slightly_smiling_face:
