### ISSUE TITLE
Fullcalendar in Georgian

### ISSUE THREAD

**Issue by sGabunia** [fullcalendar/fullcalendar-react#188]
Can I set custom language for month names and week days? Google chrome does not support 'ka' locale

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5683
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

For now you would need to use a formatting plugin. https://fullcalendar.io/docs/luxon2
