### ISSUE TITLE
Question: how can I make every square on a month view the same size?

### ISSUE THREAD

**Issue by nandorojo** [fullcalendar/fullcalendar-react#193]
Here I have the same calendar. The first is with FullCalendar. The second is my Google Calendar. Notice that the Google Calendar enforces the same height for every row. However, FullCalendar has an awkward different height per row, depending on the number of events per row. I'd like to not have this. 

**How can I make every row the same height?** I didn't see this on the sizing docs. Thank you!

<img width="1473" alt="Screen Shot 2022-05-31 at 6 17 23 PM" src="https://user-images.githubusercontent.com/13172299/171293407-203a3602-9d1f-4c5d-95b4-011c50c059a7.png">

<img width="1858" alt="Screen Shot 2022-05-31 at 6 17 11 PM" src="https://user-images.githubusercontent.com/13172299/171293408-218a1a80-6c35-4a3a-93ad-80f6d01d9fd5.png">

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5762
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by nandorojo** [comment]
Thanks @acerix! While it is indeed a duplicate of that issue, there doesn't seem to be any activity on that issue. Do you have any tips on how I may be able to patch a fix? Happy to send a PR.
