### ISSUE TITLE
Wrong date is showing in calendar 

### ISSUE THREAD

**Issue by MrFarhan** [fullcalendar/fullcalendar-react#196]
#### Issue:
The wrong date is being shown in the calendar, I have added the `2022-08-31T18:23:00.000Z` date as the start date but it is showing the event on 31st August and 1st September as well.

#### Expected outcome
it should only show the event on 31 August

#### Codesendbox link (you can see line 21 of DemoApp.jsx:
https://codesandbox.io/s/fullcalendar-v4-react-forked-vxg0en?file=/src/DemoApp.jsx

#### Screenshot:
![image](https://user-images.githubusercontent.com/26528236/187662194-9b65161c-9b59-4fb7-8f21-c2186b9bfd97.png)

**Comment by MrFarhan** [comment]
#### Is anyone looking into this issue?

**Comment by acerix** [comment]
The event time is in UTC so it is converted to your local timezone by default.  So it starts at 23:23 and it goes to the next day because the default duration is 1 hour.

You could set the end time of the event manually or change `defaultTimedEventDuration`.
