### ISSUE TITLE
Keyboard Navigation issue found for popup of events.

### ISSUE THREAD

**Issue by TheAkshayCoder** [fullcalendar/fullcalendar-react#199]
### Bug Reports

When we have more than 2 events in one day then we are rendering +more link that opens the popup.
Issue 1: Now when we are navigating via keyboard on the +more link and pressing enter when we reach on that link then that link opens and then if we press tab then we more on to other +more link and the previous +more link's popup doesn't close untill and unless we press the ESC key to close that

Issue 2: The close button for the popup is not navigable via keyboard
![image](https://user-images.githubusercontent.com/74780077/191783732-4b625630-4af7-4405-be23-c6ff101717af.png)

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/6624
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

If there is a bug, please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/).
