### ISSUE TITLE
Horizontal scroll position on timelineMonth resets when navigating to the next day

### ISSUE THREAD

**Issue by mjbour** [fullcalendar/fullcalendar-react#200]
Hi,

I'm using the timelineMonth view with React.

The scroll position of my timelineMonth is reset after the navigated to the next day.
Is there any possible solution to maintain the scrollbar position without losing it?

![image](https://user-images.githubusercontent.com/82119891/192835099-76d38e2c-f033-411b-9461-b02c09bd515a.png)

Demo app:
https://codesandbox.io/s/fullcalendar-react-forked-9bbc81?file=/src/DemoApp.jsx

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/1037
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
