### ISSUE TITLE
Custom views with `dayCount` or `visibleRange` has broken `prev` and `next`

### ISSUE THREAD

**Issue by carlomartinucci** [fullcalendar/fullcalendar-react#21]
Hi :)
I want a custom `dayGridThreeDay` views, analogous to the one described in the docs. Using `duration` (https://fullcalendar.io/docs/duration) works as expected. `visibleRange` (https://fullcalendar.io/docs/visibleRange) and `dayCount` (https://fullcalendar.io/docs/dayCount) however seems bugged.

You can easily reproduce the bug with this minimal create-react-app app: https://github.com/carlomartinucci/fullcalendar-react-views-bug

just run
```bash
git clone git@github.com:carlomartinucci/fullcalendar-react-views-bug.git
cd fullcalendar-react-views-bug
yarn install
yarn start
```

Relevant code follows:
```jsx
// App.js
import React from "react";
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import dayjs from "dayjs";

import "./calendar.scss";

const views = {
  dayGridThreeDay: {
    type: 'dayGrid',
    dayCount: 3,
    // visibleRange: (currentDate) => {
    //   return {
    //     start: dayjs(currentDate).subtract(1, 'day').format('YYYY-MM-DD'),
    //     end: dayjs(currentDate).add(2, 'day').format('YYYY-MM-DD')
    //   };
    // }
  }
}

const plugins = [dayGridPlugin];

const App = props => (
  <FullCalendar
    defaultView="dayGridThreeDay"
    views={views}
    plugins={plugins}
    events={[]}
  />
);

export default App;
```

Toggle `dayCount` and `visibleRange` to reproduce both bugs. I am using `day-js` for the `visibleRange` mode, but it is not relevant.

## Expected behaviour
both with `dayCount` or with `visibleRange`, you can click the default top left navigation buttons `prev` and `next`. Prev will shift the view one day back, next will shift the view one day forward.

## Actual behaviour with `dayCount`
clicking `next` works. Clicking `prev` once will seem to work, but clicking again will not, and clicking `next` will go 2 days forward, like you never clicked `prev` at all.

## Actual behaviour with `visibleRange`
clicking `prev` once will seems to work, but hitting it again will not change anything, and clicking `next` will go 2 days forward, just once. clicking back again will go 2 days back, just once, et cetera.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this issue is not specific to React and this existing ticket in the main repo captures this need:
https://github.com/fullcalendar/fullcalendar/issues/5319
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
