### ISSUE TITLE
FullCalendar + React, can't made selection for day which contains allDay event

### ISSUE THREAD

**Issue by anatoly314** [fullcalendar/fullcalendar-react#212]
Views become unselectable for date if this date have `allDay` event.

MVCE example here: https://codesandbox.io/s/elated-leaf-eeq5mp?file=/src/DemoApp.jsx

Without React wrapper it works fine: https://codepen.io/anatoly314/pen/ExRJRYz?editors=0010

**Comment by acerix** [comment]
The selection is prevented because of `selectOverlap` which is `true` in your first example; since the event is "all day", this prevents any selection on that day.
