### ISSUE TITLE
Changing resources prop does not update in render

### ISSUE THREAD

**Issue by panzarino** [fullcalendar/fullcalendar-react#22]
When the resources prop is changed, the calendar does not rerender. This is inconsistent with the way that the React flow works.

For example, if an async request is working in the background and it finishes, with a new resources array, and the `render()` function of the parent component is called, the calendar is not rerendered.

While the docs mention a resources function for use with ajax, this does not work with my workflow (because the information is stored in redux and used with other components), and does not align with proper React flow.

**Comment by joshuaRuff** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](https://fullcalendar.io/reduced-test-cases)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by panzarino** [comment]
@joshuaRuff I cannot post an example with codepen, jsfiddle, etc. due to the webpack requirements for FullCalendar with React. However, it is quite simple to reproduce. Render a calendar with a preset resources, then after some time, update that resources array (ex. with a button `onClick`). The despite the resources being changed in state the calendar will not render to reflect the updated state.

**Comment by mostlyfabulous** [comment]
> @joshuaRuff I cannot post an example with codepen, jsfiddle, etc. due to the webpack requirements for FullCalendar with React. However, it is quite simple to reproduce. Render a calendar with a preset resources, then after some time, update that resources array (ex. with a button `onClick`). The despite the resources being changed in state the calendar will not render to reflect the updated state.

You could fork the example react fullcalendar example here https://codesandbox.io/s/2z6wp2jozn) to reproduce the issue?

**Comment by davidrojo** [comment]
Hi @joshuaRuff , 

Here you have an example: [https://codesandbox.io/s/fullcalendar-react-bbnbl](https://codesandbox.io/s/fullcalendar-react-bbnbl)

When you click on a date, the event is moved to the date clicked. I update the state and in the render method I console.log the events state.

You can check that in console.log the event date has been modified but in the calendar the event doesn't move.

**Comment by mostlyfabulous** [comment]
Hi @davidrojo,

I noticed when you `this.setState` in the `onClick` method, you  assigned a reference to 
`const event = calendarEvents[0]` 
instead of making a new object or clone of the `calendarEvents[0]` object. This does not work because any objects in `state` are immutable. For a deeper explaination, see here: https://www.freecodecamp.org/news/handling-state-in-react-four-immutable-approaches-to-consider-d1f5c00249d5/

See here for the working fork of your example: https://codesandbox.io/s/fullcalendar-react-l73xy

**Comment by ziaulrehman40** [comment]
In my case it is actually throwing error https://github.com/fullcalendar/fullcalendar-scheduler/issues/527#issuecomment-639452902

When resources change from empty array to something else(useeffect fetches data and populates)
