### ISSUE TITLE
timeGridPlugin is broken for React (and possibly with TypeScript) - runnable code available

### ISSUE THREAD

**Issue by Hiroki111** [fullcalendar/fullcalendar-react#23]
**timeGridPlugin** isn't working for React.
To be more specific, events are not displayed within the calendar.

I've made a minimum runnable sample with `create-react-app` at `https://github.com/Hiroki111/fullcalendar-test`

After you create a folder in your machine...
`git clone git@github.com:Hiroki111/fullcalendar-test.git`
`yarn install`
`yarn start`

Then, you'll see the calendar in your browser.

![Screenshot from 2019-06-18 08-22-30](https://user-images.githubusercontent.com/9676341/59658033-c9ed1c80-91a2-11e9-8268-7f0c80ba9bf5.png)

If you scroll down to the bottom...

![Screenshot from 2019-06-18 08-22-47](https://user-images.githubusercontent.com/9676341/59658048-d70a0b80-91a2-11e9-8b96-8febec7c2d83.png)

Thank you for your help.

yarn: v1.13.0
typescript:3.4.2

**Comment by mostlyfabulous** [comment]
Based on the images and the code from the repository you shared, what would fix the event display is to include the required css styles for the timeGridPlugin:
```import '@fullcalendar/timegrid/main.css'```

**Comment by thealbertyang93** [comment]
I'm getting the same thing I imported the timegrid/main.css

**Comment by mostlyfabulous** [comment]
You'll need one other thing as well, the DayGrid css and the plugin, see here:
![image](https://user-images.githubusercontent.com/15062048/61648918-402ee400-ac65-11e9-874b-40b5f17e9010.png)
from: https://fullcalendar.io/docs/timegrid-view

**Comment by arshaw** [comment]
as you probably found out, you're missing a stylesheet.

v5 wont have this problem as stylesheets will be automatically included
