### ISSUE TITLE
Bug Schedular ReactJs

### ISSUE THREAD

**Issue by karigarweb** [fullcalendar/fullcalendar-react#25]
None of the resource view is working fine for me. All resources are broken somehow.

`import React, { Component } from 'react';
import FullCalendar from '@fullcalendar/react'
import resourceCommonPlugin from '@fullcalendar/resource-common';
import resourceDayGridPlugin from '@fullcalendar/resource-daygrid';
import resourceTimeGridPlugin from '@fullcalendar/resource-timegrid';
import resourceTimelinePlugin from '@fullcalendar/resource-timeline';
import listPlugin from '@fullcalendar/list';

class Dashboard extends Component {

    calendarComponentRef = React.createRef()
    state = {
        calendarWeekends: true,
        calendarEvents: [ // initial event data
            { title: 'Event Now', start: '2019-06-07' }
        ]
    }

    render() {
        return (
            <div className="animated fadeIn">
                <FullCalendar
                    schedulerLicenseKey="KEY-REMOVED-ON-PURPOSE"
                    now='2019-06-07'
                    allDayDefault="true"
                    aspectRatio='1.8'
                    scrollTime='00:00'
                    ref={this.state.calendarComponentRef}
                    header={this._headerOptions()}
                    resourceLabelText="Team"
                    resources={
                        [
                            { id: 'a', title: 'Auditorium A' },
                            { id: 'b', title: 'Auditorium B', eventColor: 'green' },
                            { id: 'c', title: 'Auditorium C', eventColor: 'orange' },
                            { id: 'd', title: 'Auditorium D', children: [
                                    { id: 'd1', title: 'Room D1' },
                                    { id: 'd2', title: 'Room D2' }
                                ] },
                            { id: 'e', title: 'Auditorium E' },
                            { id: 'f', title: 'Auditorium F', eventColor: 'red' },
                            { id: 'g', title: 'Auditorium G' },
                            { id: 'h', title: 'Auditorium H' },
                            { id: 'i', title: 'Auditorium I' },
                            { id: 'j', title: 'Auditorium J' },
                            { id: 'k', title: 'Auditorium K' },
                            { id: 'l', title: 'Auditorium L' },
                            { id: 'm', title: 'Auditorium M' },
                            { id: 'n', title: 'Auditorium N' },
                            { id: 'o', title: 'Auditorium O' },
                            { id: 'p', title: 'Auditorium P' },
                            { id: 'q', title: 'Auditorium Q' },
                            { id: 'r', title: 'Auditorium R' },
                            { id: 's', title: 'Auditorium S' },
                            { id: 't', title: 'Auditorium T' },
                            { id: 'u', title: 'Auditorium U' },
                            { id: 'v', title: 'Auditorium V' },
                            { id: 'w', title: 'Auditorium W' },
                            { id: 'x', title: 'Auditorium X' },
                            { id: 'y', title: 'Auditorium Y' },
                            { id: 'z', title: 'Auditorium Z' }
                        ]
                    }
                    events={
                        [
                            { id: '1', resourceId: 'b', start: '2019-06-07T02:00:00', end: '2019-06-07T07:00:00', title: 'event 1' },
                            { id: '2', resourceId: 'c', start: '2019-06-07T05:00:00', end: '2019-06-07T22:00:00', title: 'event 2' },
                            { id: '3', resourceId: 'd', start: '2019-06-06', end: '2019-06-08', title: 'event 3' },
                            { id: '4', resourceId: 'e', start: '2019-06-07T03:00:00', end: '2019-06-07T08:00:00', title: 'event 4' },
                            { id: '5', resourceId: 'f', start: '2019-06-07T00:30:00', end: '2019-06-07T02:30:00', title: 'event 5' }
                        ]
                    }
                    defaultView="listWeek"
                    plugins={
                        [
                            resourceCommonPlugin,
                            resourceTimelinePlugin,
                            resourceDayGridPlugin,
                            resourceTimeGridPlugin,
                            listPlugin
                        ]
                    } />
            </div>
        );
    }

    _headerOptions() {
        return {
            left: 'prev,next today',
            center: 'title',
            right: 'resourceTimelineWeek,resourceDayGridWeek,resourceTimeGridWeek,listWeek'
        };
    }

}

export default Dashboard;
`

You can view the broken views as on following screenshots:

**Resource Timeline:**
![image](https://user-images.githubusercontent.com/13769303/60482908-c2eb0180-9cac-11e9-944c-e2b53fa0612b.png)

**Resource Daygrid**
![image](https://user-images.githubusercontent.com/13769303/60385661-f9eec680-9aa4-11e9-89ff-7b3dfbf5a88d.png)

**Resource Timegrid**
![image](https://user-images.githubusercontent.com/13769303/60385662-0115d480-9aa5-11e9-9999-90592f961d21.png)

Following css is included in file as well:
`@import '~@fullcalendar/core/main.css';
@import '~@fullcalendar/resource-timeline/main.css';`

Just to clarify my case further, events renders perfectly fine in simple ListView that is loaded for verifying this test case.

**Comment by karigarweb** [comment]
@acerix can you please help me with this?

**Comment by pgiani** [comment]
I had the same problem, I fixed by importing the css from all componets , core , list, daygrid, timegrid, timeline and resource-timeline

Hope it helps
