### ISSUE TITLE
Giving new copy of same events array does not forces calendar to re-render

### ISSUE THREAD

**Issue by NishantDesai1306** [fullcalendar/fullcalendar-react#26]
I am using react version of this lib and I think this library is internally updating the events array which is sent as props (which is not how a react component should behave).

So I am trying to implement a basic example of resizing event, now as you can see that I am generating an array of events and I am passing it to `<FullCalendar />` which works fine but when I resize the event due to some custom logic I don't want to allow that resize operation so I am generating a new copy of the initial events array in `setState({ ... })` (line #47) call.

**Expected result**: Now as I have passed a new copy of same events array I am expecting to see no changes in calendar events because the event's start and end time are unchanged so when FullCalendar re-renders then it will create an event block at same location on calendar timeline.

**Actual Result**: Even though I am passing a new copy of events array with same start and end time values the calendar itself resizes the event, and is not re-rendering based on events array passed.
I think this library is internally updating passed events array (hence the UI gets updated) but when I pass a new copy of same array it first checks for any changes in passed events array using `deepEquals` function and as content wise there's no change in events it is not getting re-rendered.

**CodeSandbox link**: https://codesandbox.io/s/fullcalendar-react-yp2ju

**Note: Toggle `fixIssue` variable to fix the bug line #39**

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this discussion captures this need:
https://github.com/fullcalendar/fullcalendar-react/issues/65
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
