### ISSUE TITLE
I need an event to be fired as I navigate to next/previous months.

### ISSUE THREAD

**Issue by chandrahaswtw** [fullcalendar/fullcalendar-react#29]
### Bug Reports
You MUST post a recreation or else your issue will be CLOSED without explanation.
Instructions: https://fullcalendar.io/reporting-bugs

### Feature Requests
Search the issue tracker for an existing ticket before creating a new one.
Instructions: https://fullcalendar.io/requesting-features

### Is your bug/feature applicable to the core project, without React?
If so, use the main tracker: https://github.com/fullcalendar/fullcalendar/issues

(Please erase the above text and begin typing. Thanks!)

**Comment by chandrahaswtw** [comment]
I've tried using viewSkeletonRender, but this get's fired only on component load but not when I navigate through the months. Can you please guide me?

**Comment by rashid-02** [comment]
@chandrahaswtw Try this one under eventRender props of Fullcalendar.

events={(fetchInfo, successCallback, failureCallback) =>
                    getCalendarData(fetchInfo, successCallback, failureCallback)
                  }

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/3521
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
