### ISSUE TITLE
this.fullCalendar.content =null ?   why？

### ISSUE THREAD

**Issue by duanweijie** [fullcalendar/fullcalendar-react#3]
hi,i have a issue.
Create a reference to the component to use Full Calendar methods，but this.fullCalendar.content is null.

1、this.fullCalendar.content =null ?
constructor(props) {
    super(props);
    this.fullCalendar = React.createRef();  //  this.fullCalendar.content =null ?
    this.state = {
      events: []
    };
  }
2、 ref={this.fullCalendar}
 <FullCalendar
              ref={this.fullCalendar}
              id="your-custom-calendar-ID"
              header={{
                left: 'title',
                center: '',
                right: '' // agendaDay,agendaWeek,month
              }}

**Comment by mikeRead** [comment]
I haven't used .content but it seems that the this.fullcalendar hasn't been rendered yet
the flow goes constructor() -> render() -> componentDidMount() 
render() is when fullcalendar and your ref to this.fullCalendar is actually created a
Then you have real access to this.fullCalendar


this should work but I didn't test

```javascript
constructor(props) {
    super(props);
    this.fullCalendar = React.createRef(); // this.fullCalendar.content =null
    this.state = {
        events: []
    };
}
componentDidMount() {
    console.log(this.fullCalendar.content)
}

render(){
    return(
        <FullCalendar
        ref={this.fullCalendar}
        id="your-custom-calendar-ID"
            header={{
            left: 'title',
            center: '',
            right: '' // agendaDay,agendaWeek,month
        }}>
    )
}
```
