### ISSUE TITLE
How separate between days on the week view with fullcalendar react?

### ISSUE THREAD

**Issue by IchrakMansour** [fullcalendar/fullcalendar-react#35]
I have a `FullCalendar` :

```
import FullCalendar from "@fullcalendar/react";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";

// must manually import the stylesheets for each plugin

import "@fullcalendar/core/main.css";
import "@fullcalendar/daygrid/main.css";
import "@fullcalendar/timegrid/main.css";


<FullCalendar 
                   locale={frLocale}
                   allDaySlot={false}
            defaultView="timeGridWeek"
            nowIndicator={true}
            hiddenDays={[0]}
            slotDuration='00:45:00'
            minTime="07:00:00"
            maxTime="20:00:00"
            slotEventOverlap={false}
            handleWindowResize={true}
            header={{
              left: "prev,next today",
              center: "title",
              right: "dayGridMonth,timeGridWeek,timeGridDay"
            }}
            plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin ]}
            ref={this.calendarComponentRef}
           // weekends={true}
            events={this.state.events}
            dateClick={this.newEvent}
            eventLimit={true}
            displayEventEnd={true}

          />
```

when I run  it, I get: 

![image](https://user-images.githubusercontent.com/36265843/69733937-72c67d00-112e-11ea-8860-4faf19ae18da.png)

I want to separate between days like a yellow line : 

![image](https://user-images.githubusercontent.com/36265843/69733874-59253580-112e-11ea-80f2-c61ebdd36f02.png)

My `package.json` :

[![enter image description here][1]][1]

I try to add this css :

    .fc-timeGrid-view .fc-time-grid tbody tr:nth-of-type(even) {
        background: rgba(246, 246, 246, 0.667);
    }
    
    .fc-timeGrid-view .fc-widget-content {
      border-right: 2px solid #EE7 !important;
    }
    
    .fc-timeGrid-view .fc-widget-content:first-child {
      border-right: inherit !important;
    }

But it doesn't working.

How can I fix it ? 

  [1]: https://i.stack.imgur.com/ob7lj.png

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4864
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by Maadtin** [comment]
@acerix That has nothing to do with this issue :S

**Comment by MircoSans** [comment]
Im having the same problem.
<img width="967" alt="image" src="https://user-images.githubusercontent.com/51395487/202246005-5210d417-e80f-4bc0-acf7-31d3133e1a08.png">

**Comment by MircoSans** [comment]
"@fullcalendar/daygrid": "^5.11.3",
        "@fullcalendar/interaction": "^5.11.3",
        "@fullcalendar/react": "^5.11.2",
        "@fullcalendar/timegrid": "^5.11.3",
