### ISSUE TITLE
events function rendering on all eventsClick

### ISSUE THREAD

**Issue by YaraRammal** [fullcalendar/fullcalendar-react#37]
I have this <FullCalendar/>  where 
events call the getCalendarData() that returns in the SuccessCallback the array of appointments that should be displayed.

But the issue is that this method is being rendered 3 times.

Also when EventClick (that opens a popup) is being clicked, the getCalendarData() is being called 12 times for no reason.

```
      <FullCalendar
                  defaultView="dayGridMonth"
                  header={{
                    left: "prev,next today",
                    center: "title",
                    right: ""
                    // dayGridMonth,listWeek"
                  }}
                  plugins={[
                    dayGridPlugin,
                    timeGridPlugin,
                    interactionPlugin,
                    bootstrapPlugin,
                    listPlugin
                  ]}
                  ref={calendarComponentRef}
   
                  dateClick={openDateList}
                  editable={true}
                  eventStartEditable={false}
                  eventResizableFromStart={true}
                  eventDurationEditable={true}
                  dragRevertDuration={true}
                  eventLimit={4}
                  slotDuration={30}
                  eventClick={seeEventAppointment}
                  events={(fetchInfo, successCallback, failureCallback) =>
                    getCalendarData(fetchInfo, successCallback, failureCallback)
                  }
                  //   events={calendarEvents}
                />
```

**Comment by rashid-02** [comment]
@YaraRammal Please check if you are calling that function twice in anywhere of your code and make sure you are not calling it under useEffect() function.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

Please post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/) if there is still an issue. Would really appreciate it because the time saved reproducing will be time spent fixing.
