### ISSUE TITLE
Documentation issue with css imports

### ISSUE THREAD

**Issue by saurabhnemade** [fullcalendar/fullcalendar-react#38]
### Bug Reports
Css import section on https://fullcalendar.io/docs/react says we need to import only 
```
@import '~@fullcalendar/core/main.css';
@import '~@fullcalendar/daygrid/main.css';
```

however I found out the timeline grid css is also required otherwise week and day plugin ui breaks.
Could you please update documentation with following?

```
@import '~@fullcalendar/core/main.css';
@import '~@fullcalendar/daygrid/main.css';
@import "~@fullcalendar/timegrid/main.css";
```

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

Each view has it's own CSS file that needs to be included to use the view, this page lists them:

https://fullcalendar.io/docs/plugin-index

This has also been simplified in version 5 to avoid having to manually include them.
