### ISSUE TITLE
Is there any way to fetch events data on prev/next click of calendar?

### ISSUE THREAD

**Issue by rashid-02** [fullcalendar/fullcalendar-react#39]
### Feature Requests
Kindly explain which method/function to be call to implement this feature. which callback functions are able to return values on changing the month that can be us to fetch events data dynamically from API.

**Comment by sami616** [comment]
Very valid question, right now the only way i see is via `datesRender` which isnt idea seeing as it fires on every render. are there plans to add something like a `onNavigateDates` callback prop?

**Comment by janchimugica** [comment]
Having the same issue and looking for a solution. I invoke a modal pop-up on eventClick and it re-renders the Calendar, which refetches the events on both opening and closing the modal.

**Comment by Moglum** [comment]
Maybe you can find some inspiration in this small example with MobX - https://codesandbox.io/s/mobx-react-fullcalendar-xejn9
The idea is to store the events primarily in a local store - Events - and have fullcalendar get events from this store whenever it needs to using the `events` prop. 
Notice in the example when exactly does the calendar request events from the `events` function prop (it logs to Console)
Any fetching of events from an API could happen in the store if needed. The store acts as a cache of sorts.

>Even when using eventClick to open a modal pop-up it refetches the events both when opening and closing the modal.
Opening and closing a modal should not trigger a re-render of the fullcalendar component, look for a better modal component if it's causing re-renders (it worked for me both with https://github.com/reactjs/react-modal or https://material-ui.com/components/dialogs/)

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this discussion captures this need:
https://github.com/fullcalendar/fullcalendar-react/issues/65
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
