### ISSUE TITLE
Calendar does not initially resize to fit events rendered with ReactDOM.render

### ISSUE THREAD

**Issue by saurabhnemade** [fullcalendar/fullcalendar-react#46]
`updateSize()` function is not called initially if eventRenderer is used. because of this, we see overflow of events on first render.
Its a little bit weird. only on first render its not working. On window resize its working fine.

You can see the behaviour at : https://stackblitz.com/edit/react-ewzzac?file=Hello.js
<img width="1658" alt="Screenshot 2020-02-17 at 3 17 54 PM" src="https://user-images.githubusercontent.com/17445338/74642343-d3e37700-5198-11ea-9312-b5723b2f59fa.png">

**Comment by tuancaraballo** [comment]
I'm experiencing the exact same, I had to limit the number of events being displayed

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

Thanks for the demo, also reproduced in debug template:

https://codesandbox.io/s/fullcalendar-v4-react-qn3rf?file=/src/DemoApp.jsx

You could try calling `updateSize` manually as a workaround.

**Comment by acerix** [comment]
I just noticed this existing ticket for the same issue:
https://github.com/fullcalendar/fullcalendar-react/issues/12
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Comment by jakeotoolespok** [comment]
> Sorry for the delay in responding to your issue, I have just begun triaging on this repo. Please see this post about the state of the repo (#66) for more info.
> 
> Thanks for the demo, also reproduced in debug template:
> 
> https://codesandbox.io/s/fullcalendar-v4-react-qn3rf?file=/src/DemoApp.jsx
> 
> You could try calling `updateSize` manually as a workaround.

I think I'm mostly overthinking, but how would I access `updateSize`? I want to resize my calendar, but not because events are overflowing, the calendar isn't taking up the full container on initial render. If I make any changes like flip dates, update events, etc, it corrects itself.
![image](https://user-images.githubusercontent.com/71281583/129769677-ac37a966-a210-4116-9e4c-96ce3f386121.png)

**Comment by dmdum** [comment]
> **UPDATE:** I figured out how to access `updateSize()` in React. It is located on the Calendar API. ex: `calendar.updateSize()`
> 
> Unfortunately, this didn't help solve my issue. I found that my parent component had a CSS transition effect on it and that is what caused the initial render of the calendar to not be properly sized. When the transition ends I render the calendar.
> 
> How to get `.updateSize()` in React
> 
> * You need to gain access to the Calendar API. There are two main ways.
> 
> 1. By creating a ref to the calendar component with `useRef` or `createRef` as documented [here](https://fullcalendar.io/docs/react#calendar-api).
> 2. Many of the callbacks pass in an arg with the View API. The Calendar API can be found within the View API.
> 
> ```js
>  const onEventClick =  (eventInfo) => {  
>   
>    const calendar = eventInfo.view.calendar;
>    calendar.updateSize();
> 
>  }
> ```
> 
> I think I'm mostly overthinking, but how would I access `updateSize`? I want to resize my calendar, but not because events are overflowing, the calendar isn't taking up the full container on initial render. If I make any changes like flip dates, update events, etc, it corrects itself.
> 
> I tried creating a `ref` to the Calendar and seeing if it was maybe a `prop`, but didn't have any luck. Would I have to like extend the FullCalendar Class? ![image](https://user-images.githubusercontent.com/71281583/129769677-ac37a966-a210-4116-9e4c-96ce3f386121.png)

@jakeotoolespok 
Having the same problem...
Did you find any solution for this?

**Comment by sarveshh** [comment]
I finally found a solution for this.

In my case, Tthis was happening because my Side navigation was opened at the time of inital rendering. But when I minimised it, it turned into this.

Before:
![image](https://github.com/fullcalendar/fullcalendar-react/assets/63977074/43b50ecc-454a-4d17-9823-1bc1bbfcd795)

**Solution** : I maintained a state that checked if side navigation was open or not. And changed `aspectRatio` prop accordingly. Just like this.
![image](https://github.com/fullcalendar/fullcalendar-react/assets/63977074/1e5b4802-dd73-4e7d-b30f-bd721214e03c)

**Comment by niklaslennartsson** [comment]
> I finally found a solution for this.
> 
> In my case, Tthis was happening because my Side navigation was opened at the time of inital rendering. But when I minimised it, it turned into this.
> 
> Before: ![image](https://private-user-images.githubusercontent.com/63977074/264245013-43b50ecc-454a-4d17-9823-1bc1bbfcd795.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNTkzNDksIm5iZiI6MTcwNTE1OTA0OSwicGF0aCI6Ii82Mzk3NzA3NC8yNjQyNDUwMTMtNDNiNTBlY2MtNDU0YS00ZDE3LTk4MjMtMWJjMWJiZmNkNzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDE1MTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NGJkZDYxMTI0YTZkYjY4YTJkYmNlOWJkYzE4Y2U3ODE2NjNmNjY0ZmNlMzBmYjQ5Yjc3MmU0OTg0ZGE3YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KRBOChNgF9uDq3VyF5hb6v88vIHo3mha3JQiUehWCqA)
> 
> **Solution** : I maintained a state that checked if side navigation was open or not. And changed `aspectRatio` prop accordingly. Just like this. ![image](https://private-user-images.githubusercontent.com/63977074/264246017-1e5b4802-dd73-4e7d-b30f-bd721214e03c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNTkzNDksIm5iZiI6MTcwNTE1OTA0OSwicGF0aCI6Ii82Mzk3NzA3NC8yNjQyNDYwMTctMWU1YjQ4MDItZGQ3My00ZTdkLWIzMGYtYmQ3MjEyMTRlMDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDE1MTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNzlmM2I4ZWJhOTI0ZTEzYzc0NjcxNmM3NGEyZWZkYjhkODZmMmE3MzkyMmRmZTRiMjJhM2JkNzU2ZTFjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QjuJgi9E8SY4e7UIPWJnBh6RK4xRiDKFQZd1AuDjYiw)

@sarveshh 
This works only when the height is not set to 100%. The aspect ratio changes when both the height and total width change. In my situation, I also have a side navigation that automatically collapses based on the window size and can be collapsed by clicking. However, the view does not have a maximum width, so it can accommodate various sizes. Therefore, the aspect ratio is not suitable for my needs.

**Comment by niklaslennartsson** [comment]
I fixed it by faking a window resize. Even though FullCalendar is supposed to catch window resizes when the handleWindowResize prop is true, in my case, the window doesn't really resize; it's the inner divs/wrappers that change. But by pretending to resize with a little delay (to let the sidebar transition finish), it works now.

    useEffect(() => {
        setTimeout(() => {
            window.dispatchEvent(new Event('resize'));
        }, 150);
    }, [menuCollapse])
