### ISSUE TITLE
Duplicated events rendered on the calendar after external drag and drop 

### ISSUE THREAD

**Issue by mnob2019** [fullcalendar/fullcalendar-react#47]
Hi, not sure if this is a bug or I am stupid. Here is the codesandbox:

https://codesandbox.io/s/strange-pine-5xkre

Expected behavior that the one event will be rendered and saved in the state, however I am getting duplicated events after I am using eventRecieve triggered after the external drop.

**Comment by Ryanauger95** [comment]
Did you ever figure out a solution?

**Comment by mnob2019** [comment]
@Ryanauger95  Hi, yes, a but a trick one though, I still do not know how to do that properly))  You can see below that I remove the "empty" event from the calendar right away after creation. Then the calendar reproduces the actual one. Let me know what you think.
handleeventRecieve=(info)=>{
  const calendar = this.calendarComponentRef.current.getApi();
calendar.getEventById(info.event.id).remove()
  const id=uuid()

  this.setState({
    calendarEvents:this.state.calendarEvents.concat({
      // creates a new array
      title: info.event.title,
      start: info.event.start,
      end:new Date(moment(info.event.start).add(0.5, 'hour').valueOf()),
      id:id
    })

});

return  this.state.calendarEvents

}

**Comment by Ryanauger95** [comment]
Oh man im getting the same issue! Why is this?? This is crazy behavior.

**Comment by Ryanauger95** [comment]
my on event recieve is called twice

**Comment by Ryanauger95** [comment]
That's the core issue. For some reason it is called twice

**Comment by mostlyfabulous** [comment]
@mnob2019 The problem you face is the drop callback being fired all the time which probably modifies the calendar object. Then, your custom eventReceive callback runs adding the second event, at the same time, only that the event added now has end time unlike the event made by the drop callback.

![Annotation 2020-03-22 010726](https://user-images.githubusercontent.com/15062048/77245127-8adc7380-6bd9-11ea-97de-6d3ddafead87.png)

**Comment by mnob2019** [comment]
@mostlyfabulous Hi! Thank you so much for your help! I was doing  all this work around, it worked but felt really wrong

**Comment by clive-h-townsend** [comment]
This seems to work. Unfortunately though, it doesn't show the little preview image as you are dragging it, correct?

**Comment by mostlyfabulous** [comment]
@clive-h-townsend 
It should show a preview as you drag, maybe the browser you're using doesn't support it?
See the screenshot below:
![Annotation 2020-04-23 172850](https://user-images.githubusercontent.com/15062048/80162380-0db16f00-8588-11ea-8cb8-7f75ea11a035.png)

**Comment by clive-h-townsend** [comment]
Hi, yes. Thanks for the follow-up. I do have the shaded piece now. When you are clicking and dragging, there is the event that is a bit more apparent and "snappy" but this works well enough. Thanks for the post and the help!

**Comment by arshaw** [comment]
I believe this issue is related to improper state management between React and FullCalendar. This sort of state-management stuff is easy to get wrong because the FullCalendar docs have not defined any best practices. I have written a doc proposing two standard techniques. Could you please take a look at it and write a comment, or at least a 👍 ? I REALLY REALLY appreciate fast feedback because I'm trying to get this nailed down for the v5 release in the next few days!

Proposal: [Event-data conventions!?](https://github.com/fullcalendar/fullcalendar-react/issues/65)

PS- apologies for [neglecting this repo](https://github.com/fullcalendar/fullcalendar-react/issues/66)

**Comment by anhhd2703** [comment]
I am sorry but I have a problem. if I used "drop" I can't get the ID of element dropped.
How can I get all the data of the element.
