### ISSUE TITLE
In NextJs Element not defined error

### ISSUE THREAD

**Issue by usha-raikwar** [fullcalendar/fullcalendar-react#48]
### Bug Reports
In next Js app I get erro element not defined 

ReferenceError: Element is not defined
reactive-framework:     at C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\node_modules\@fullcalendar\core\main.js:108:25
reactive-framework:     at C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\node_modules\@fullcalendar\core\main.js:8:68
reactive-framework:     at Object.<anonymous> (C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\node_modules\@fullcalendar\core\main.js:11:2)
reactive-framework:     at Module._compile (internal/modules/cjs/loader.js:1144:30)
reactive-framework:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
reactive-framework:     at Module.load (internal/modules/cjs/loader.js:993:32)
reactive-framework:     at Function.Module._load (internal/modules/cjs/loader.js:892:14)
reactive-framework:     at Module.require (internal/modules/cjs/loader.js:1033:19)
reactive-framework:     at require (internal/modules/cjs/helpers.js:72:18)
reactive-framework:     at Object.@fullcalendar/core (C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\packages\ethos-app\.next\server\static\development\pages\_app.js:11317:18)
reactive-framework:     at __webpack_require__ (C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\packages\ethos-app\.next\server\static\development\pages\_app.js:23:31)
reactive-framework:     at Module../src/Components/Organisms/Calendar/Calendar.tsx (C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\packages\ethos-app\.next\server\static\development\pages\_app.js:6773:76)
reactive-framework:     at __webpack_require__ (C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\packages\ethos-app\.next\server\static\development\pages\_app.js:23:31)
reactive-framework:     at Module../src/Components/Organisms/index.ts (C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\packages\ethos-app\.next\server\static\development\pages\_app.js:9584:76)
reactive-framework:     at __webpack_require__ (C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\packages\ethos-app\.next\server\static\development\pages\_app.js:23:31)
reactive-framework:     at Module../src/Components/Templates/Layout/Layout.tsx (C:\Users\Usha\Documents\Github\reactive\FIS_UX_platform\packages\ethos-app\.next\server\static\development\pages\_app.js:9623:68)
reactive-framework: 

### Is your bug/feature applicable to the core project, without React?
If so, use the main tracker: https://github.com/fullcalendar/fullcalendar/issues

(Please erase the above text and begin typing. Thanks!)

**Comment by ta-toshio** [comment]
this would be work.

CalendarNoSsr.tsx
```
import dynamic from 'next/dynamic'

export default dynamic(
  () => import('./Calendar'),
  { ssr: false }
)
```

Calendar.tsx
https://github.com/fullcalendar/fullcalendar-example-projects/blob/master/react-typescript/src/DemoApp.tsx

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar/issues/4784
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
