### ISSUE TITLE
Events as functions not called on state change?

### ISSUE THREAD

**Issue by cjsjyh** [fullcalendar/fullcalendar-react#53]
I'm not sure if this is the intended behavior but my function in `eventSources` is not fired when the component has been rerendered due to state change.
```
<FullCalendar 
        slotDuration='00:30:00'
        businessHours={businessHours}
        timeZone='Asia/Seoul'
        ref={this.calendarRef}
        locale={koLocale} 
        defaultView="timeGridWeek" 
        plugins={[timeGridPlugin, listPlugin, interactionPlugin]}
        eventAllow={this.eventAllowance}
        eventLimit={true}
        eventDurationEditable={true}
        editable={true}
        droppable={true}
        buttonIcons={true}
        eventSources={[this.loadScheduleFromApi]}
        eventClick={this.eventClick}
        eventDrop={this.eventUpdateTime}
        eventResize={this.eventUpdateTime}
        drop={this.externalEventDrop}
        select={this.select}
        allDaySlot={false}
        selectable={true}
        header={{
                left: "prev,next today",
                center: "title",
                right: "timeGridDay,timeGridWeek,listMonth"
        }}
 />
```

I tried calling `refetch()` myself on state change but this triggers another render because of state change and another render trigger refetch and repeating infinitely

```
if(this.calendarRef && this.calendarRef.current){
        let eventSources = this.calendarRef.current.calendar.getEventSources()
        eventSources[0].refetch()
}
```

I want my eventSource function to be fired on both date change and state change. How can I achieve this? Also is there a way to distinguish whether eventSource function has been fired by date change or state change?(possibly send custom argument?)

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just began triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this discussion captures this need:
https://github.com/fullcalendar/fullcalendar-react/issues/65
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
