### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by Ryanauger95** [fullcalendar/fullcalendar-react#55]
Is anyone maintaining this repo? Drag and drop is broken, issues are very stale. I would just love if I could ask someone a few questions, I am happy forking the repo and working on it but I would love if the people who built it could point me in the right direction...

**Comment by tranchem** [comment]
I think you should write issue in main repo: [https://github.com/fullcalendar/fullcalendar/issues](url)

**Comment by arshaw** [comment]
hey @Ryanauger95 , thanks for asking this! The answer is no! Sorry about the radio silence. I wrote a quick response to you and others wondering about this.

State of this repo (#66)
