### ISSUE TITLE
setState in function select

### ISSUE THREAD

**Issue by tranchem** [fullcalendar/fullcalendar-react#56]
Hi, I'm very grateful for fullcalendar-react!
![issue-fullcalendar](https://user-images.githubusercontent.com/43035967/76931036-6e5ee380-691a-11ea-9e81-6135fefd263d.PNG)
This is my problem when setState any params in function select.

**Comment by abelmcelroy** [comment]
I am also having this issue. Any idea when this issue began?

**Comment by Moglum** [comment]
4.3.1 works fine https://codesandbox.io/s/fullcalendar-functional-430-mydrf
4.4.0 breaks it https://codesandbox.io/s/fullcalendar-functional-440-z5fqn

**Comment by abelmcelroy** [comment]
Thanks @Moglum! I ended up reverting to 4.2 yesterday to fix it, but you're totally right and your post really helpful.

**Comment by Moglum** [comment]
And if you use React class component instead of functional to wrap FullCalendar it works even with 4.4.0 🤯
https://codesandbox.io/s/fullcalendar-class-7u48i

**Comment by Moglum** [comment]
I have created an issue in the core component, since nothing has changed in the react component betwee 4.3.0 - 4.4.0
https://github.com/fullcalendar/fullcalendar/issues/5315

**Comment by tranchem** [comment]
> I am also having this issue. Any idea when this issue began?

This issue is resolved in [https://github.com/fullcalendar/fullcalendar/issues/5270](url)
Let use calendarApi.unselect();

**Comment by bryanrtboy** [comment]
> This issue is resolved in [https://github.com/fullcalendar/fullcalendar/issues/5270](url)
> Let use calendarApi.unselect();

calendarApi.unselect(); does not work for me in 5.0.0-beta.2 with this same problem. Create a function for a header button, this works fine:
`  gotoFall = () => {
    let calendarApi = this.calendarComponentRef.current.getApi();
    calendarApi.gotoDate("2020-08-17");
  };`

Any function with setState creates an error (all event titles disappear, but the event blocks remain in place)
`  toggleVA = () => {
    let calendarApi = this.calendarComponentRef.current.getApi();
    calendarApi.unselect();
    this.setState({
      showVisualArts: !this.state.showVisualArts
    });`
The 'showVisualArts' property updates fine, and clicking the button toggles back and forth as expected. In the browser inspector, I can see the event titles were deleted.  I'm using events as a function to load the data.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

I believe this ticket in the main repo is for the same issue which was fixed in version 4.4.1 which was just releasd:
https://github.com/fullcalendar/fullcalendar/issues/5266
