### ISSUE TITLE
Help : wrapper for reactj 15.6

### ISSUE THREAD

**Issue by titoff002** [fullcalendar/fullcalendar-react#61]
Hello,

Do you have a version of your wrapper for version 15.6 of reactjs? If yes, can you give me the link? If not: how to make this wrapper.

Thank you.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

This page explains how to use the React component which is now on version 16:

https://fullcalendar.io/docs/react
