### ISSUE TITLE
Bug Report: eventRender crashes the application

### ISSUE THREAD

**Issue by KeranenJukka** [fullcalendar/fullcalendar-react#62]
Hi,

Here is the problem:
- I am using timeGridPlugin and interactionPlugin with fullcalendar-react
- Fullcalendar has eventRender function
- When you click the calendar it fires a function which has regular setState function
- Application crashes
- TypeError: Cannot read property 'calendar' of undefined
- If you remove setState or eventRender, application does not crash

Here is the CodeSandbox link:

https://codesandbox.io/s/fullcalendar-react-giswe

**Comment by mostlyfabulous** [comment]
A work-around for the bug is to use version 4.3.0 for all of the following:

- @fullcalendar/interaction
- @fullcalendar/react
- @fullcalendar/timegrid

See here:
https://codesandbox.io/s/fullcalendar-react-x46sn?file=/src/App.js

**Comment by KeranenJukka** [comment]
Thanks. Works now like it should. Is this bug going to be fixed in the future?

**Comment by arshaw** [comment]
version 4.4.2 was just released which contains a fix for this.
fixed repro: https://codesandbox.io/s/fullcalendar-react-b59ng?file=/src/App.js

if there are any further issues, please make a new ticket
