### ISSUE TITLE
Events on multiple days causing a CSS issue

### ISSUE THREAD

**Issue by iElsha** [fullcalendar/fullcalendar-react#64]
Hello,

I am having an issue when I want to add a full-day event to the calendar.

**Full Calendar config**
```
    "@fullcalendar/core": "^4.4.0",
    "@fullcalendar/daygrid": "^4.4.0",
    "@fullcalendar/interaction": "^4.4.0",
    "@fullcalendar/react": "^4.4.0",
    "@fullcalendar/timegrid": "^4.4.0",
```

I removed every unrelated stylesheets and JS files, 3rd party libraries & server-side logic and tested with JSON. It is working.
However, when I add the server-side logic (fetching data in the json only), there is a CSS bug happening:
![Screenshot from 2020-05-06 13-07-27](https://user-images.githubusercontent.com/38140638/81170216-92de5000-8f9a-11ea-8e87-2b09fa013017.png)

I check from if it could come from the event props given to the Calendar :
```json
[
			{
				"id": "FIxlCYD1FRKBux3eM8pC",
				"isHoliday": true,
				"title": "Vacance",
				"start": "2020-05-07T10:00:00.031Z",
				"end": "2020-05-08T10:00:00.034Z",
				"backgroundColor": "#FF4DFA"
			},
			{
				"id": "2020-05-09_07:00_Ostéopathie_Articulaire",
				"title": "Articulaire qzd qzd",
				"start": "2020-05-09T07:00:00.000Z",
				"end": "2020-05-09T07:30:00.000Z",
				"backgroundColor": "#4D63FF",
				"extendedProps": {
					"time": "2020-05-09T07:00:00.000Z",
					"name": "qzdqzd qzdqzd",
					"type": "Ostéopathie",
					"treatment": "Articulaire",
					"isFirst": "Non",
					"phone": "06 05 04 34 91",
					"mail": "zqdzqdzd@outlook.fr"
				}
			}
		]
```

The bug happened once the data are loaded from the server, then I change view with the arrow and come back on the one where's there the ping event (multiple days). And the glitch happens.
Maybe it's because I'm not adding this event properly?
```js
 events.push({
                id: holiday.id,
                isHoliday:true,
                title: "Vacance",
                start: timeFrom.toISOString(),
                end: timeTo.toISOString(),
                backgroundColor: HOLIDAY_COLOUR
            });
... (then there's a this.setState())...
```

However, I didn't succeed to find why there is this CSS bug... It's happening in Firefox and chrome (didn't test other browsers). I'm pretty sure it's in my side code but I don't know where and why it's happening.

Thank you in advance for your help.

**Comment by acerix** [comment]
Sorry for the delay in responding to your issue, I have just begun triaging on this repo. Please see this post about the state of the repo (https://github.com/fullcalendar/fullcalendar-react/issues/66) for more info.

Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
