### ISSUE TITLE
Event-data conventions!?

### ISSUE THREAD

**Issue by arshaw** [fullcalendar/fullcalendar-react#65]
FullCalendar has not established a clear convention for React users (nor Vue/Angular users) for providing event data to their calendars, which is a little bit ridiculous. This has led to many improvised approaches which often have shortcomings like double-rendering events or being at odds with React's declarative nature.

I'm proposing two patterns that I will eventually add to the docs. They require some additional API tweaks (see proposals below), but hopefully they are immediately readable as pseudocode. The sample code is based off the v5 api, [which is currently in beta](https://fullcalendar.io/docs/v5/upgrading-from-v4). The sample code displays a simple month-view calendar with events loaded from a server and also displays a plain text list of events below, along with an "add event" button.

Please comment on this issue or at least give a 👍  if you approve.

## Technique 1: FullCalendar owns the event data

```js
import * as React from 'react'
import FullCalendar from '@fullcalendar/react'

//
// FullCalendar OWNS THE EVENT DATA, meaning:
// FullCalendar requests the data from a feed,
// FullCalendar manipulates the data for drag-n-drop/resize.
//
class DemoApp extends React.Component {

  calendarRef = React.createRef()
  state = {
    currentRefinedEvents: [] // events parsed by FullCalendar
  }
 
  render() {
    return (
      <div>
        <FullCalendar
          ref={this.calendarRef}
          initialView='dayGridMonth'
          editable={true}
          events='/events/query' // a remote JSON feed that will receive start/end params
          eventsDidUpdate={this.handleEventsDidUpdate} // eventsDidUpdate not-yet-implemented (see proposal)
        />
        <h2>Current Event List:</h2>
        <ul>
          {this.state.currentRefinedEvents.map((refinedEvent) => (
            <li>{refinedEvent.title} - {refinedEvent.start.toISOString()}</li>
          ))}
        </ul>
        <button onClick={this.handleAddEventToday}>
          add an event today!
        </button>
      </div>
    )
  }

  handleEventsDidUpdate = (arg) => {
    if (arg.addedEvent) { // an EventApi object
      request('/events/add', JSON.stringify(arg.addedEvent)) // requires EventApi::toJSON (see proposal)

    } else if (arg.updatedEvent) { // an EventApi object
      request('/events/update', JSON.stringify(arg.updatedEvent)) // requires EventApi::toJSON (see proposal)

    } else if (arg.removedEvent) { // an EventApi object
      request('/events/remove', { id: arg.removedEvent.id })
    }
    // There's a final condition for when events are received from the server
    // (the arg.loadedEvents array will be populated)
    //
    // For any of these scenarios (add/update/delete/loaded),
    // give DemoApp the parsed event data...
    this.setState({ currentRefinedEvents: arg.allEvents })
  }

  handleAddEventToday = () => {
    let calendarApi = this.calendarRef.current.getApi()
    calendarApi.addEvent({
      title: 'event that happens today',
      start: new Date()
    })
  }

}
```

## Technique 2: DemoApp owns the event data

```js
import * as React from 'react'
import FullCalendar from '@fullcalendar/react'
import { requestJson, request } from './utils' // please imagine these

//
// DemoApp OWNS THE EVENT DATA, meaning:
// DemoApp requests and parses the data data from a feed,
// DemoApp manipulates the data for drag-n-drop/resize.
//
class DemoApp extends React.Component {

  state = {
    currentRefinedEventMap: {} // an {id:event} hash of parsed events
  }

  render() {
    return (
      <div>
        <FullCalendar
          initialView='dayGridMonth'
          editable={true}
          datesDidUpdate={this.handleDatesDidUpdate}
          events={this.state.currentRefinedEventMap} // accepting a hash not-yet-implemented (see proposal)
          eventsDidUpdate={this.handleEventsDidUpdate} // eventsDidUpdate not-yet-implemented (see proposal)
        />
        <h2>Current Event List:</h2>
        <ul>
          {Object.values(this.state.currentRefinedEvents).map((refinedEvent) => (
            <li>{refinedEvent.title} - {refinedEvent.start.toISOString()}</li>
          ))}
        </ul>
        <button onClick={this.handleAddEventToday}>
          add an event today!
        </button>
      </div>
    )
  }

  // called when the calendar's data are initially set, or when they change
  handleDatesDidUpdate = (arg) => {
    requestJson('/events/query', {
      start: arg.view.activeRange.start.toISOString(),
      end: arg.view.activeRange.end.toISOString()
    }).then((rawEvents) => {
      this.setState({
        currentRefinedEventMap: buildRefinedEventMap(rawEvents)
      })
    })
  }

  handleEventsDidUpdate = (arg) => {
    if (arg.addedEvent) { // an EventApi object
      this.addEvent(arg.addedEvent)

    } else if (arg.updatedEvent) { // an EventApi object
      this.updateEvent(arg.updatedEvent)

    } else if (arg.removedEvent) { // an EventApi object
      this.removeEvent(arg.removedEvent)
    }

    // returning false will prevent FullCalendar from recording these changes internally.
    // this is desirable because our setState call will modify currentRefinedEventMap,
    // which will be passed to FullCalendar anyway.
    return false
  }

  handleAddEventToday = () => {
    this.addEvent(
      parseRawEvent({
        title: 'event that happens today',
        start: new Date()
      })
    )
  }

  addEvent(event) { // event might have been refined by DemoApp OR FullCalendar
    request('/events/add', JSON.stringify(event)) // requires EventApi::toJSON (see proposal)
    this.setState({
      currentRefinedEventMap: addOrUpdateEventMap(
        this.state.currentRefinedEventMap,
        event
      )
    })
  }

  updateEvent(event) { // event might have been refined by DemoApp OR FullCalendar
    request('/events/update', JSON.stringify(event)) // requires EventApi::toJSON (see proposal)
    this.setState({
      currentRefinedEventMap: addOrUpdateEventMap(
        this.state.currentRefinedEventMap,
        event
      )
    })
  }

  removeEvent(event) { // event might have been refined by DemoApp OR FullCalendar
    request('/events/remove', { id: event.id })
    this.setState({
      currentRefinedEventMap: deleteFromEventMap(
        this.state.currentRefinedEventMap,
        event
      )
    })
  }

}

// event data-manipulation methods
// (this logic would probably be in your reducer)
// ----------------------------------------------

function buildRefinedEventMap(rawEvents) {
  let map = {}

  for (let rawEvent of rawEvents) {
    let refinedEvent = parseRawEvent(rawEvent)
    
    if (refinedEvent) {
      map[refinedEvent.id] = refinedEvent
    } else {
      console.warn('Invalid event data', rawEvent)
    }
  }

  return map
}

function parseRawEvent(rawEvent) {
  if (rawEvent.id && rawEvent.start) { // TODO: could be much more stringent
    return {
      id: rawEvent.id,
      title: rawEvent.title,
      start: new Date(rawEvent.start), // parses an ISO8601 date in most browsers
      end: rawEvent.end ? new Date(rawEvent.end) : null // (same)
    }
  }
}

function addOrUpdateEventMap(map, event) {
  return {
    ...map,
    [event.id]: event.toJSON() // returns a plain object. not-yet-implemented (see proposal)
  }
}

function deleteFromEventMap(map, event) {
  let mapCopy = { ...map }
  delete mapCopy[event.id]
  return mapCopy
}
```

## Apendix

Proposed API changes to make the above code possible:

- [events/eventSources should accept an object map](https://github.com/fullcalendar/fullcalendar/issues/5442)
- [handler for when any event data changes - eventsDidUpdate](https://github.com/fullcalendar/fullcalendar/issues/5441)
- [Event toJSON and toPlainObject methods](https://github.com/fullcalendar/fullcalendar/issues/5440)

**Comment by mnob2019** [comment]
Yes, it was a bit misleading for me when I had  duplicated events, It was really hard to find the documentation about this and I had  to work around

**Comment by clive-h-townsend** [comment]
I mean just taking a glance at this, I'm not sure why you wouldn't write this with React hooks given that they are so popular after release 16.8... We've got almost all core FullCalendar functionality with very minor workarounds... i.e. these two lines fixed a lot of issues: 

        const calendarApi = CalendarRef.current.getApi()
        calendarApi.unselect()

Not sure you should jam through changes at the last minute to v5 without being really deliberate with them. Just some worked through React-centric examples would have saved us 90% of the implementation time.

**Comment by arshaw** [comment]
@clive-h-townsend, don't get too hung up on examples with hooks versus classed-based components. The point is to demonstrate two approaches: one where the FullCalendar component owns the data, the other where the outer app owns it. I want to gauge whether people would see themselves using one of these two approaches, or if there are other use cases I'm not thinking of.

Thanks for the code, but I'm not sure what problem it was meant to solve. I'll need more context in order to understand.

I'm mainly just trying to decide what I should write in the V5 docs. I'm also trying to decide whether I should add-in the utility methods mentioned in the Appendix of my proposal. They are minor and would be useful outside of any React usage anyway. If I add them, they will be present in the next beta, not a rushed final release. I won't officially release anything if it's not ready.

It would be really useful to me if you could take a second look at the two scenarios above and let me know they matched how you ended up implementing your project. Did you have have FullCalendar own the event data, or higher up in your app?

**Comment by Phibedy** [comment]
Technique 2 would be really great. In react you don't want some children-component to own data, because you always have to sync it with its parent. It would be a great improvement 👍

**Comment by hanselke** [comment]
pretty sure its better design to handle it via the parent as in use case 2. we'd need the data in the parent , and to pass in a function declared in the parent to act on button clicks.

**Comment by vanch3d** [comment]
Tend to agree with Technique 2, as with previous comments. Found myself in very similar situation with having some dirty tricks in place to avoid duplicated events (not sure I even identified every situation they occur) when manipulating the calendar (using 4.4). 
My main data source is in a Redux store, events are also modified through other components in the app, and would appreciate an approach that keeps the elegance of the single-source-of-truth design.

**Comment by hanselke** [comment]
so after working with it a while more, i think i understand the issue better.

Currently you have to handle the state of events within the component, as you would need drag and drop of events to be handled.

I'm currently only passing calendarEvents to the component via componentDidMount, and not doing anything on componentDidUpdate. 
(I pass actions to the component, which are converted to this.state.calendarEvents)

Modifying app data via calendar actions are handled by calendar event hooks, and i essentially ignore the updates passed down the wire.

Seems to work. Can you foresee any problems with this?

**Comment by Moglum** [comment]
The 2nd use case would be amazing, storing a single master copy of the events outside of the calendar seems like a cleaner solution for an interactive calendar app. But I can totally see Use case 1 be useful for perhaps simpler scenarios.

I personally prefer MobX for managing state and if I understand it correctly (but I might be completely off) this would allow me to directly pass a MobX @observable or @computed hash with events to the calendar and make it react to changes in the events in the MobX store. And to handle all calendar-caused event changes with 1 handler - `eventsDidUpdate` back to the MobX store. Currently, I have to use the `event` function to fetch the events from the MobX store and some other trick to force a re-render of the calendar component. 
Like for example here https://codesandbox.io/s/mobx-react-fullcalendar-xejn9?file=/src/Calendar.jsx it's the `<ul>` list of events that actually observes the store and causes the re-render and the event function handler to be called. Otherwise only changing the calendar view or dates will fetch new events, kinda beating the purpose of MobX.

**Comment by hanselke** [comment]
> The 2nd use case would be amazing, storing a single master copy of the events outside of the calendar seems like a cleaner solution for an interactive calendar app. But I can totally see Use case 1 be useful for perhaps simpler scenarios.
> 
> I personally prefer MobX for managing state and if I understand it correctly (but I might be completely off) this would allow me to directly pass a MobX @observable or @computed hash with events to the calendar and make it react to changes in the events in the MobX store. And to handle all calendar-caused event changes with 1 handler - `eventsDidUpdate` back to the MobX store. Currently, I have to use the `event` function to fetch the events from the MobX store and some other trick to force a re-render of the calendar component.
> Like for example here https://codesandbox.io/s/mobx-react-fullcalendar-xejn9?file=/src/Calendar.jsx it's the `<ul>` list of events that actually observes the store and causes the re-render and the event function handler to be called. Otherwise only changing the calendar view or dates will fetch new events, kinda beating the purpose of MobX.


It would be awesome if it can hook in natively to a mobx @observable and essentially have the component modify the mobx store. 

Maybe what could be done is to pass a saveDataMethod prop to the calendar library, which then allows us to pass any sort of function that the calendar uses to save events data? This would allow us to pass a default of this.setState for simpler apps, so that the state is set at the parent level?

**Comment by bryanrtboy** [comment]
Bear in mind, I'm a beginner in both React and FullCalendar!  

In the app I am developing, I think option #2 would make the most sense. It's a resource scheduling app and I am getting the room use data via an API. The calendar view is amazing, and is why I really enjoy using full-calendar. The other views I use are lists, and I find that it works best for me to parse the API, populate a state with calendar events in the main App.jsx.  Calendar uses that state for it's events and resources.
Currently, it seems to work best to unmount the Calendar, and re-mount after a new fetch of data. Ideally, Calendar would just re-populate when the state changes that holds the events without any workaround in the App.

**Comment by epitaphmike** [comment]
I definitely think #2 is the best approach. I think the FullCalendar should consume data and handle the event changes. I look at the calendar like a form (local state). On initial load the calendar has no data. It is the apps responsibility to fetch the data and populate the calendar based on the calendars API. This would be the calendars initial state. This state can be local like a form and live in context, or global to the app like a Redux/MobX approach. I prefer a local state. For most forms this would be a number of empty input fields unless you are let's say editing a record, where you would populate the input fields the the fetched data to edit. At the end of the day, I think the app should do the state management, not the calendar.

This data that is fetched for the calendar goes into the state. When the calendar it edited, eg. drag and drop or resized, that event's data updates the state and it's the apps responsibility to handle the state change, whether it be trigger a post to a rest endpoint or mutation for GraphQL. 

Either way, I think the calendar should consume the data and handle the event changes, while the app should retrieve the data and save the new data based on event changes or user triggered actions.

I am curious to hear your opinion on the separation of concerns between the app and the FullCalendar component.

**Comment by arshaw** [comment]
Thanks for the input everyone.

One thing I might not have made clear about approach 1: even though the FullCalendar component would be the source of truth for the event data, it would still be possible to pass this data up the component hierarchy when it changes, via callbacks.

Also, nobody seems to have touched on this scenario: what if you have an enormous database of events and you only want the client to be aware of events that are in the current date range? You'd be dependent on the current UI state of the calendar for this. This is a scenario where it'd be more convenient for FullCalendar to fetch and own its own data because it's aware of its own date range.

Anyway, I'll stop banging on about approach 1. Approach 2 seems to be the favorite :)

I've made the necessary API changes to make both approaches much easier to implement compared to v4. They are in the new [v5 release candidate](https://fullcalendar.io/blog/2020/06/v5-rc-new-features) and are mostly listed in [this section of the upgrade guide](https://fullcalendar.io/docs/v5/upgrading-from-v4#event-manipulation).

I've also created two example projects to demonstrate:

1) [Approach 1](https://github.com/fullcalendar/fullcalendar-example-projects/tree/v5/react)
2) [Approach 2](https://github.com/fullcalendar/fullcalendar-example-projects/tree/v5/react-redux) (with Redux)

Some notes about [what's happening in approach 2](https://github.com/fullcalendar/fullcalendar-example-projects/blob/v5/react-redux/src/DemoApp.jsx): When a user-action initiates an add/change/delete, the example calls various FullCalendar API methods in order to render the changes immediately. This is better than having to wait for a network request to complete before rendering, which looks bad. These user actions get funneled to `eventAdd`/`eventChange`/`eventRemove` which then dispatch the actions to the reducer. If the action should fail, the changes are reverted with each callback's `revert` method.

Anyway, hope this all makes sense. Please lmk if questions.

**Comment by Phibedy** [comment]
Why approach 1 is rather difficult for me:
1. I have a large database with a lot of events, but also a calendar-filter and fetch only data that passes the filter already in the backend
2. There is also another component where you can bulk-select/modify events in a list view. For example change in 100 Events the attendees at once. The component should not need to fetch its own data as it shares the filter with the calendar
3. If you want to calculate statistics based on shown events it is also easier if the events are in the parent

Nevertheless implementation 1 seems to great for viewers with not to much possible user interaction :+1: 

What I like about your implementation 2:
* https://github.com/fullcalendar/fullcalendar-example-projects/blob/v5/react-redux/src/DemoApp.jsx#L32 That what I asked for v5 in https://github.com/fullcalendar/fullcalendar/issues/3521 :+1: 
* https://github.com/fullcalendar/fullcalendar-example-projects/blob/v5/react-redux/src/DemoApp.jsx#L91 The temporary events are great for user experience if the user has a bad internet connection :)

**Comment by Moglum** [comment]
I have created https://github.com/fullcalendar/fullcalendar-example-projects/pull/13 with a very simple MobX/Typescript example for Approach 2. 
It's not using `datesSet` but could be easily added, to manage the visible date range in the store and maybe use it to pre-filter events passed to the Calendar.

**Comment by bryanrtboy** [comment]
I can see your point about approach #1. I am fetching a large dataset (course schedules), but they are repeating events only.  The filtering is by subject, not date, so it still seems like #2 works best for me. My current approach is to 'fetch everything', and then the App filters based on the filters the user has set. This means one large fetch per semester, but then the data is instant in Calendar or non-Calendar views.

**Comment by arshaw** [comment]
thanks again for the input everyone. I'm closing this issue because everything I mentioned in my previous comment has been [officially released](https://fullcalendar.io/blog/2020/06/v5-official)

**Comment by Phibedy** [comment]
Is Technique 2 implemented?

**Comment by Mihai-github** [comment]
Would be very nice to have a more React-style implementation to know for example if data is loaded or React docs because the ones that are available are kinda hard to read and take many let's say try and errors until you may or may not find what you are looking for...

Anyway... is there a way to know if the data was loaded inside the calendar? From what i can see there is none
