### ISSUE TITLE
resourceTimelineWeek change dayTimeLine to fail

### ISSUE THREAD

**Issue by conkyliu** [fullcalendar/fullcalendar-react#69]
source:https://github.com/conkyliu/fullcalendar-demo.git
video:
[video(5).MP4.zip](https://github.com/fullcalendar/fullcalendar-react/files/4700088/video.5.MP4.zip)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
