### ISSUE TITLE
Possible Issue with dragging  and dropping external calendar events

### ISSUE THREAD

**Issue by abhiram5** [fullcalendar/fullcalendar-react#7]
I can able to drag and drop external events into calendar but how to get all the events which are on calender  ?

**Comment by bshiroya** [comment]
Hi @abhiram5 Could you please share external event drag and drop example in react over here ?

**Comment by milkysingh** [comment]
@abhiram5 It'll be really great if you could share the working example fo external drag and drop on codesandbox or jsfiddle.

**Comment by joshuaRuff** [comment]
@abhiram5  @bshiroya can you please share an example where you are able to reproduce this issue with an example of your code please.

**Comment by abhiram5** [comment]
Hi @joshuaRuff 

Thanks for your response,

is there any method or function to get all the events which are present on the calendar?

**Comment by joshuaRuff** [comment]
@abhiram5 Normally events are supplied by you to the calendar. Please provide me with more information on how you are importing events into the calendar.
