### ISSUE TITLE
Calendar layout breaks after updating with setState

### ISSUE THREAD

**Issue by Khanbhai1990** [fullcalendar/fullcalendar-react#70]
Hello,
first of this is a fantastic library so thank you for building it :) I have downloaded the version 4.4.2 and there seems to an issue with callback functions datesRender and viewSkeletonRender. I would like to track the date changes and save it to my state, but when I setState to save the latest date change the calendar styling goes off. Not sure what is causing this -- datesDestroy callback works fine but I would like to know the latest date since I use that info to make calls to backend to get additional events and be one step ahead of the user.

<img width="1341" alt="Screen Shot 2020-06-03 at 2 59 30 PM" src="https://user-images.githubusercontent.com/29368029/83696611-c4eecc00-a5b1-11ea-910f-063f9ac0fb6a.png">

calendar size height kinda collapses and timegrid breaks as well

<img width="1330" alt="Screen Shot 2020-06-03 at 2 59 59 PM" src="https://user-images.githubusercontent.com/29368029/83696673-e51e8b00-a5b1-11ea-8b5a-35ce92f83979.png">

**Comment by Khanbhai1990** [comment]
Bug Replicated in codesandbox. Hitting "next" button will mess the styling up. Seem like using setState is the culprit, even though I didn't even change values of the state.
[https://codesandbox.io/s/fullcalendar-react-w1inr?file=/src/DemoApp.jsx](url)

**Comment by acerix** [comment]
Thanks, confirmed.  

It should work using methods like [changeView](https://fullcalendar.io/docs/Calendar-changeView) instead of `setState`.  

Since the layout gets fixed after a resize, you could also trigger that manually as a workaround:

https://codesandbox.io/s/fullcalendar-react-ot9vd

**Comment by arshaw** [comment]
hey @Khanbhai1990 or @acerix , any way you can see if this is happening in v5-beta? there are v5-beta repro templates [here](https://fullcalendar.io/reduced-test-cases)

**Comment by echountasis** [comment]
The same behavior happens when you implement the datesRender. If you don't implement the specific event the layout is ok, but  if you do then it breaks after changing date. Not sure if it is related with your issue.

**Comment by Khanbhai1990** [comment]
@Khanbhai1990 
I didn't come across this bug in v5-beta 👍

**Comment by echountasis** [comment]
I upgraded also to beta v-5 and the issue seems to be solved.

**Comment by arshaw** [comment]
great!

btw, the release candidate is out: https://fullcalendar.io/blog/2020/06/v5-rc-new-features
