### ISSUE TITLE
Issues with scrollbars in resource timeline

### ISSUE THREAD

**Issue by plutocow** [fullcalendar/fullcalendar-react#72]
Hi, just testing out the resource timeline functionality and am running into several issues.

Firstly, it looks like there is a scrollbar in every column? Is there a way to remove this?
Example image shown: ![](https://i.imgur.com/qnjlzTV.png)

Also, the scrollbar appears to be disabled, I cannot scroll in spots such as the "year" view. 
The codesandbox has been included below:
https://codesandbox.io/s/autumn-cherry-gsj77

**Comment by acerix** [comment]
It's missing the CSS file `timeline/main.css`

https://codesandbox.io/s/wispy-haze-857v7?file=/src/App.js
