### ISSUE TITLE
MobX Store @observable variables are null when the calendar events are raised.

### ISSUE THREAD

**Issue by echountasis** [fullcalendar/fullcalendar-react#74]
It seems that I cannot use the actions in MobX from your events. More specifically, I have implemented the below
select={(data: any) => createEvent(data)}
and in the mobx store I have this 

    @action createEvent(event: any) {
        console.log(event);

        runInAction(() =>
            this.events.push(event)
        )

    }

The console.log works finr but then an exception is thrown that the "events" is null while it is not.

Any idea how it could be solved? Issue exist in 4.4.2 and beta 5
![Untitled](https://user-images.githubusercontent.com/14096267/84685144-0d0ad880-af3a-11ea-9776-1c11c3e673c1.png)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by echountasis** [comment]
I have uploaded a sample project the reproduce the issue here https://github.com/echountasis/MobXAndFullCalendar-issue.git

Just click on an empty date, this will call the createEvent that adds an event in the list of events used from the calendar.

Thank you for your help and well done for the component you have created!

**Comment by echountasis** [comment]
I made a commit and the issue is fixed (that was a bug from my side). Now i see that the event is pushed successfully into the list but since the calendar is not an observer it is not shown. Any idea how i could refresh the calendar or insert it?

By using calendarComponentRef.current.addEvent(<event data>) it gives an exception the addEvent is not a function.

**Comment by echountasis** [comment]
You can leave the issue closed. To access the add event I had to go like that calendar._calendarApi.addEvent(newevent).

Not sure if that is your intention but is working!
