### ISSUE TITLE
full-calendar-v5 RC CSS causing build failure

### ISSUE THREAD

**Issue by ericodom** [fullcalendar/fullcalendar-react#75]
I was super excited to see fullcalendar-react hit the release candidate milestone!  Unfortunately, the new css system seems to have some problems with our theme we use.

I'm no expert on webpack stuff, but I know the theme does us a webpack build system, cssloders, etc.  It already includes the Material UI JSS stuff as well as Tailwind.css.  But as soon as I import in the full-calendar component into a page the project will no longer compile and I get the following error:

**Failed to compile.

./node_modules/@fullcalendar/common/main.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@fullcalendar/common/main.css)
ParserError: Syntax Error at line: 1, column 45**

I was hoping someone has seen an error like this before and could help me out here.  I've included a stripped down project repository for review: 

https://github.com/ericodom/fuse-full-calendar

The page in question is located at "src->app->main->example->Example.js"

Just need to uncomment the full-calendar import and you'll get the build error.

I really hope someone has an idea here...we've been using the full-calendar control since version 1 and we're in the process of moving everything to React, and this is the final piece to the conversion!

Thanks!
Eric

**Comment by arshaw** [comment]
dup of:
https://github.com/fullcalendar/fullcalendar/issues/5503
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
