### ISSUE TITLE
Cannot read property 'isHiddenDay' of undefined

### ISSUE THREAD

**Issue by seyacat** [fullcalendar/fullcalendar-react#78]
### Bug Reports
I dont know what happens, but on update calendar stop to work, i really dont know what to do

Uncaught TypeError: Cannot read property 'isHiddenDay' of undefined
    at new DaySeriesModel (app.js:19206)
    at DayTableView.buildDayTableModel (app.js:10771)
    at DayTableView.buildDayTableModel (app.js:12087)
    at DayTableView../node_modules/@fullcalendar/daygrid/main.js.DayTableView.render (app.js:10760)
    at finishClassComponent (app.js:120137)
    at updateClassComponent (app.js:120087)
    at beginWork (app.js:121597)
    at HTMLUnknownElement.callCallback (app.js:103165)
    at Object.invokeGuardedCallbackDev (app.js:103214)
    at invokeGuardedCallback (app.js:103269)
DaySeriesModel @ app.js:19206
buildDayTableModel @ app.js:10771
(anonymous) @ app.js:12087
./node_modules/@fullcalendar/daygrid/main.js.DayTableView.render @ app.js:10760
finishClassComponent @ app.js:120137
updateClassComponent @ app.js:120087
beginWork @ app.js:121597
callCallback @ app.js:103165
invokeGuardedCallbackDev @ app.js:103214
invokeGuardedCallback @ app.js:103269
beginWork$1 @ app.js:126180
performUnitOfWork @ app.js:125134
workLoopSync @ app.js:125107
performSyncWorkOnRoot @ app.js:124733
scheduleUpdateOnFiber @ app.js:124165
updateContainer @ app.js:127350
(anonymous) @ app.js:127735
unbatchedUpdates @ app.js:124880
legacyRenderSubtreeIntoContainer @ app.js:127734
render @ app.js:127817
./resources/js/components/Calendar.js @ app.js:132301
__webpack_require__ @ app.js:20
./resources/js/app.js @ app.js:132039
__webpack_require__ @ app.js:20
0 @ app.js:132585
__webpack_require__ @ app.js:20
(anonymous) @ app.js:84
(anonymous) @ app.js:87
app.js:122504 The above error occurred in the <DayTableView> component:
    in DayTableView (created by CalendarContent)
    in div (created by ViewContainer)
    in ViewContainer (created by CalendarContent)
    in CalendarContent (created by CalendarRoot)
    in div (created by CalendarRoot)
    in CalendarRoot (created by CalendarDataProvider)
    in CalendarDataProvider (created by FullCalendar)
    in FullCalendar (created by Calendar)
    in div (created by Calendar)
    in Calendar

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by seyacat** [comment]
Why you close?

**Comment by acerix** [comment]
We need a way to reproduce the bug, I can reopen it when you supply a demo.

**Comment by jennifererwangg** [comment]
I am facing the same issue. I used npx create-react-app and downloaded all the @fullcalendar plugins. I then copied + pasted the react app from the examples. And I faced this bug. It came from the DayGridPlugin and TimeGridPlugin (whenever I call timeGridDay and basically anything with Grid).

**Comment by anubhavsahoo** [comment]
The bug can be reproduced by following the demo steps
```
git clone https://github.com/fullcalendar/fullcalendar-example-projects.git
cd fullcalendar-example-projects/react
npm install
npm run start 
```
Seems like there is some issue with the latest version v5.20

Managed to make this work by rolling back the version of all fullcalendar modules to 5.1.0
Dont forget to reset node modules:
```
rm -rf node_modules/@fullcalendar/*
npm i
npm start --reset-cache
```

**Comment by arshaw** [comment]
@anubhavsahoo, I tried the steps you mention, with the latest version 5.3.0, and I can't produce the error.

FYI, version 5.3.0 [had an issue](https://github.com/fullcalendar/fullcalendar/issues/5778) where it put the wrong version text in the build JS files. Maybe you were unknowingly using 5.3.0.

Everyone, please follow this issue on the main issue tracker for further developments:
https://github.com/fullcalendar/fullcalendar/issues/5592
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
