### ISSUE TITLE
navLinks prop error when going to day view

### ISSUE THREAD

**Issue by Maadtin** [fullcalendar/fullcalendar-react#85]
Hello here's the link to the bug:

https://codesandbox.io/s/fullcalendar-w87of?file=/src/App.js

This happens ofcourse when you enable navLinks to true via the prop.

What's happening is that when clicking in any navLink it goes to the day but it renders as a blank page without any cell.

**Comment by acerix** [comment]
It's not obvious why it's not working in your demo, but it works as expected in the debug template, so doesn't seem like a bug in the calendar:

https://codesandbox.io/s/compassionate-feistel-8en45

**Comment by Maadtin** [comment]
Hi @acerix the only difference is that im not using the headerToolbar prop but the fullcalendar api to change the views and the current date 😅 aside from that im not doing anything different.
