### ISSUE TITLE
Event Source fetching data on every keystroke even when a modal is opened on dateSelect and information is added into that model.

### ISSUE THREAD

**Issue by Malikx-Alee** [fullcalendar/fullcalendar-react#89]
I am displaying an Modal on the date select and when i start typing details in that modal it starts re-fetching data on every keystroke. Which sends too many requests that event source consume a lot time in displaying data until the response from last request is received.

I need only the data being fetched after i close the modal.

```
<FullCalendar
            className="my-calendar"
            plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin]}
            eventContent={renderEventContent} // custom render function
            initialView="timeGridDay"
            headerToolbar={{
              left: "prev,next today",
              center: "title",
              right: "dayGridMonth,timeGridWeek,timeGridDay",
            }}
            slotDuration={timeSlot}
            eventBackgroundColor="rgba(0, 119, 128, 0.05)"
            eventTextColor="#007780"
            nowIndicator={true}
            dayCellClassNames={"day-cell-background"}
            scrollTime={scrollTime}
            dayMaxEvents={true}
            select={handleDateSelect}
            eventClick={handleEventClick}
            editable={true}
            selectable={true}
            contentHeight={windowDimensions.height - 200}
            longPressDelay={5}
            eventSources={[
              {
                url: `My Source URL`,
                failure: function () {
                  alert("there was an error while fetching events!");
                },
              },
            ]}
          />
```

here is the code sandbox link: https://codesandbox.io/s/boring-fermi-536xx?file=/src/App.js

![91160312-af85cb80-e6e2-11ea-9564-2700b09e5afc](https://user-images.githubusercontent.com/28903531/91969589-c86c2d80-ed2f-11ea-9942-6d00eacc9998.png)

**Comment by acerix** [comment]
It seems that happens becuse you are updating the state on each field's "onChange", it should work as you want if you update the state when the form is submitted instead.

**Comment by Malikx-Alee** [comment]
@acerix  How to show a loader? I have used the loading prop in the calendar. The calendar refetch data on the state change and if i set the state of the loader it refetch data again and causes a infinite loop.
