### ISSUE TITLE
when allDay is true event coloring doesnt work 

### ISSUE THREAD

**Issue by shamseerahammedm** [fullcalendar/fullcalendar-react#90]
https://codesandbox.io/s/github/fullcalendar/fullcalendar-example-projects/tree/master/react?file=/src/DemoApp.jsx

this is a sandbox link given in the documentation when all day is true , coloring event is not working 

```
id: eventItem.id,
title: eventItem.subject,
start: moment(eventItem.event_start).format('Y-MM-DD'),
end: endData,
editable: true,
hasAttachments: true,
allDay: false,
eventStart : eventItem.event_start,
backgroundColor: '#32c2d9',
borderColor: '#CBF5D4',
textColor: 'white',
```

this doesnt work color comes as default grey color for all events fetched and displayed in calendar, allDay is false 

```
id: eventItem.id,
title: eventItem.subject,
start: moment(eventItem.event_start).format('Y-MM-DD'),
end: endData,
editable: true,
hasAttachments: true,
allDay: true,
eventStart : eventItem.event_start,
backgroundColor: '#32c2d9',
borderColor: '#CBF5D4',
textColor: 'white',
```
this works since allDay is true 

what is the problem ?

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.
