### ISSUE TITLE
fullcalendar in react-native?

### ISSUE THREAD

**Issue by andrejm7** [fullcalendar/fullcalendar-react#98]
Hello friends.

does fullcalendar work with react-native?

I had a problem that when importing into my project says that it was not possible to find main.js

**Comment by acerix** [comment]
I believe this existing ticket captures this need:
https://github.com/fullcalendar/fullcalendar-react/issues/34
↑
Please visit the above issue, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
